-- These tables are used by barricade to manage authentication

-- migrate:up
CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    openid_sub VARCHAR NOT NULL UNIQUE, 
    email VARCHAR NOT NULL UNIQUE, 
    first_name VARCHAR, 
    last_name VARCHAR, 
    system_admin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Give access to the application user, the application user has no access to 
-- The sessions table and therefore cannot fake a login.
GRANT SELECT, UPDATE, INSERT ON users TO bionic_application;
GRANT USAGE, SELECT ON users_id_seq TO bionic_application;

-- Give access to the readonly user
GRANT SELECT ON users, users_id_seq TO bionic_readonly;

-- Manage the updated_at column
SELECT updated_at('users');

-- migrate:down
DROP TABLE users;