-- migrate:up

CREATE TABLE document_pipelines (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    dataset_id INT NOT NULL,
    user_id INT NOT NULL,
    team_id INT NOT NULL, 
    name VARCHAR NOT NULL,
    api_key VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_user FOREIGN KEY(user_id)
        REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT FK_team FOREIGN KEY(team_id)
        REFERENCES teams(id) ON DELETE CASCADE,

    CONSTRAINT FK_dataset FOREIGN KEY(dataset_id)
        REFERENCES datasets(id) ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON document_pipelines TO bionic_application;
GRANT USAGE, SELECT ON document_pipelines_id_seq TO bionic_application;

-- migrate:down
DROP TABLE document_pipelines;

