-- migrate:up

CREATE TABLE api_keys (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id INT NOT NULL,
    name VARCHAR NOT NULL,
    api_key VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_prompt FOREIGN KEY(prompt_id)
        REFERENCES prompts(id) ON DELETE CASCADE
);

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON api_keys TO ft_application;
GRANT USAGE, SELECT ON api_keys_id_seq TO ft_application;

-- Give access to the readonly user
GRANT SELECT ON api_keys TO ft_readonly;
GRANT SELECT ON api_keys_id_seq TO ft_readonly;


-- migrate:down

DROP TABLE api_keys;