-- migrate:up
CREATE TABLE objects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL, 
    object_name VARCHAR(100) NOT NULL,
    object_data BYTEA, -- Consider offloading to external storage
    mime_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL, -- To handle larger file sizes
    file_hash VARCHAR(32) NOT NULL, -- Assuming MD5
    created_by INT NOT NULL, 
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- migrate:down
DROP TABLE objects;