-- migrate:up

CREATE TABLE audit_trail_api_generation (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    audit_id INT NOT NULL, 
    api_key_id INT NOT NULL, 
    tokens_sent INT NOT NULL,
    tokens_received INT NOT NULL,
    time_taken INT NOT NULL,

    CONSTRAINT fk_api_key
        FOREIGN KEY(api_key_id) 
        REFERENCES api_keys(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_audit
        FOREIGN KEY(audit_id) 
        REFERENCES audit_trail(id)
        ON DELETE CASCADE
);


COMMENT ON TABLE audit_trail_api_generation IS 'Capture API Text Generation';

-- Grant access
GRANT SELECT, INSERT ON audit_trail_api_generation TO bionic_application;
GRANT USAGE, SELECT ON audit_trail_api_generation_id_seq TO bionic_application;

GRANT SELECT ON audit_trail_api_generation TO bionic_readonly;
GRANT SELECT ON audit_trail_api_generation_id_seq TO bionic_readonly;

-- migrate:down
DROP TABLE audit_trail_api_generation;

