-- migrate:up
CREATE TABLE objects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL REFERENCES teams(id) ON DELETE CASCADE, 
    object_name VARCHAR(100) NOT NULL,
    object_data BYTEA, -- Consider offloading to external storage
    mime_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL, -- To handle larger file sizes
    file_hash VARCHAR(32) NOT NULL, -- Assuming MD5
    created_by INT NOT NULL REFERENCES users(id) ON DELETE CASCADE, 
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE prompts DROP COLUMN image_icon;
ALTER TABLE prompts ADD COLUMN image_icon_object_id INT;

GRANT SELECT, INSERT ON objects TO bionic_application;
GRANT USAGE, SELECT ON objects_id_seq TO bionic_application;
GRANT SELECT ON objects TO bionic_readonly;
GRANT SELECT ON objects_id_seq TO bionic_readonly;

-- migrate:down
DROP TABLE objects;

ALTER TABLE prompts ADD COLUMN image_icon BYTEA;
ALTER TABLE prompts DROP COLUMN image_icon_object_id;