-- migrate:up

CREATE TABLE api_chats (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    api_key_id INT NOT NULL, 
    prompt VARCHAR NOT NULL, 
    response VARCHAR, 
    status chat_status NOT NULL DEFAULT 'Pending',
    tokens_sent INT NOT NULL,
    tokens_received INT NOT NULL DEFAULT 0,
    time_taken_ms INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_api_key
        FOREIGN KEY(api_key_id) 
        REFERENCES api_keys(id)
        ON DELETE CASCADE
);


COMMENT ON TABLE api_chats IS 'Capture API Text Generation';

-- Manage the updated_at column
SELECT updated_at('api_chats');

-- Grant access
GRANT SELECT, INSERT, UPDATE ON api_chats TO bionic_application;
GRANT USAGE, SELECT ON api_chats_id_seq TO bionic_application;

GRANT SELECT ON api_chats TO bionic_readonly;
GRANT SELECT ON api_chats_id_seq TO bionic_readonly;

-- migrate:down
DROP TABLE api_chats;

