-- migrate:up

CREATE TABLE limits (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limits_role VARCHAR,
    user_email VARCHAR,
    model_id INT,
    tokens_per_hour INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_model FOREIGN KEY(model_id)
        REFERENCES models(id) ON DELETE CASCADE
);

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON limits TO bionic_application;
GRANT USAGE, SELECT ON limits_id_seq TO bionic_application;

-- Give access to the readonly user
GRANT SELECT ON limits TO bionic_readonly;
GRANT SELECT ON limits_id_seq TO bionic_readonly;


-- migrate:down

DROP TABLE limits;