-- migrate:up
CREATE TABLE api_key_connections (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_id int NOT NULL REFERENCES integrations(id) ON DELETE CASCADE,
    user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    team_id int NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    visibility visibility NOT NULL,
    api_key text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW()
);

-- Permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON api_key_connections TO bionic_application;
GRANT USAGE, SELECT ON api_key_connections_id_seq TO bionic_application;

-- migrate:down
DROP TABLE api_key_connections;