-- migrate:up

CREATE TABLE translations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locale TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT translations_locale_key_unique UNIQUE (locale, key)
);

GRANT SELECT ON translations TO application_user;
GRANT SELECT ON translations TO application_readonly;

INSERT INTO translations (locale, key, value) VALUES
    ('en', 'i18n.ai_assistants', 'AI Assistants'),
    ('en', 'i18n.integrations', 'Integrations'),
    ('en', 'i18n.integration', 'Integration'),
    ('en', 'i18n.prompts', 'Explore Assistants'),
    ('en', 'i18n.datasets', 'Datasets & Documents'),
    ('en', 'i18n.assistants', 'Assistants'),
    ('en', 'i18n.assistant', 'Assistant'),
    ('en', 'i18n.dataset', 'Dataset');

-- migrate:down

DROP TABLE IF EXISTS translations;
