-- migrate:up

CREATE TYPE integration_type AS ENUM (
    'MCP_Server'
);
COMMENT ON TYPE integration_type IS 'The type of integration.';

CREATE TABLE integrations (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    integration_type integration_type NOT NULL,
    name VARCHAR NOT NULL, 
    base_url VARCHAR NOT NULL, 
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON integrations TO bionic_application;
GRANT USAGE, SELECT ON integrations_id_seq TO bionic_application;

-- Give access to the readonly user
GRANT SELECT ON integrations TO bionic_readonly;
GRANT SELECT ON integrations_id_seq TO bionic_readonly;

-- migrate:down
DROP TABLE integrations;
DROP TYPE integration_type;