-- migrate:up

CREATE TABLE openapi_specs (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    spec JSONB NOT NULL,
    logo_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- Permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON openapi_specs TO application_user;
GRANT USAGE, SELECT ON openapi_specs_id_seq TO application_user;

GRANT SELECT ON openapi_specs TO application_readonly;
GRANT SELECT ON openapi_specs_id_seq TO application_readonly;

-- migrate:down
DROP TABLE openapi_specs;
