-- migrate:up
DO $$ BEGIN
    ALTER TYPE model_type ADD VALUE 'Guard';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TYPE model_capability ADD VALUE 'Guarded';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TYPE prompt_flag_type AS ENUM (
    'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7',
    'S8', 'S9', 'S10', 'S11', 'S12', 'S13', 'S14'
);

CREATE TABLE prompt_flags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    flag_type prompt_flag_type NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON prompt_flags TO application_user;
GRANT SELECT ON prompt_flags TO application_readonly;

-- migrate:down
DROP TABLE prompt_flags;
DROP TYPE prompt_flag_type;
