-- migrate:up

CREATE SCHEMA scheduled_tasks;
GRANT USAGE ON SCHEMA scheduled_tasks TO application_user;
GRANT USAGE ON SCHEMA scheduled_tasks TO application_readonly;

CREATE TYPE scheduled_task_run_status AS ENUM ('pending', 'running', 'completed', 'failed');

CREATE TABLE scheduled_tasks.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    team_id INT NOT NULL REFERENCES iam.teams(id) ON DELETE CASCADE,
    project_id INT REFERENCES projects.projects(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    prompt TEXT NOT NULL,
    cron TEXT NOT NULL,
    timezone TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    next_run_at TIMESTAMPTZ NOT NULL,
    last_run_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX scheduled_tasks_due_idx ON scheduled_tasks.tasks (next_run_at)
    WHERE enabled = TRUE;

CREATE TABLE scheduled_tasks.runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES scheduled_tasks.tasks(id) ON DELETE CASCADE,
    scheduled_for TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    status scheduled_task_run_status NOT NULL DEFAULT 'pending',
    error TEXT,
    conversation_id BIGINT REFERENCES llm.conversations(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT scheduled_tasks_runs_task_scheduled_for_key UNIQUE (task_id, scheduled_for)
);

CREATE INDEX scheduled_tasks_runs_task_id_idx ON scheduled_tasks.runs (task_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON scheduled_tasks.tasks TO application_user;
GRANT USAGE, SELECT ON scheduled_tasks.tasks_id_seq TO application_user;
GRANT SELECT ON scheduled_tasks.tasks TO application_readonly;
GRANT SELECT ON scheduled_tasks.tasks_id_seq TO application_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON scheduled_tasks.runs TO application_user;
GRANT USAGE, SELECT ON scheduled_tasks.runs_id_seq TO application_user;
GRANT SELECT ON scheduled_tasks.runs TO application_readonly;
GRANT SELECT ON scheduled_tasks.runs_id_seq TO application_readonly;

SELECT updated_at('scheduled_tasks.tasks');


-- migrate:down

DROP TABLE scheduled_tasks.runs;
DROP TABLE scheduled_tasks.tasks;
DROP TYPE scheduled_task_run_status;
DROP SCHEMA scheduled_tasks;
