-- migrate:up
CREATE TABLE llm.generated_outputs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id INT NOT NULL REFERENCES llm.conversations(id) ON DELETE CASCADE,
    object_id INT NOT NULL REFERENCES storage.objects(id) ON DELETE CASCADE,
    path TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    file_hash VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(conversation_id, path)
);

SELECT updated_at('llm.generated_outputs');

GRANT SELECT, INSERT, UPDATE, DELETE ON llm.generated_outputs TO application_user;
GRANT USAGE, SELECT ON llm.generated_outputs_id_seq TO application_user;
GRANT SELECT ON llm.generated_outputs TO application_readonly;
GRANT SELECT ON llm.generated_outputs_id_seq TO application_readonly;


-- migrate:down
DROP TABLE IF EXISTS llm.generated_outputs;
