-- migrate:up
ALTER TABLE datasets ADD COLUMN is_project BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE projects (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL,
    dataset_id INT NOT NULL,
    name VARCHAR NOT NULL,
    instructions TEXT NOT NULL DEFAULT '',
    visibility visibility NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT FK_projects_team FOREIGN KEY(team_id)
        REFERENCES teams(id) ON DELETE CASCADE,

    CONSTRAINT FK_projects_dataset FOREIGN KEY(dataset_id)
        REFERENCES datasets(id) ON DELETE CASCADE,

    CONSTRAINT FK_projects_user FOREIGN KEY(created_by)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX projects_dataset_id_idx ON projects(dataset_id);

ALTER TABLE conversations ADD COLUMN project_id INT;
ALTER TABLE conversations
    ADD CONSTRAINT FK_project FOREIGN KEY(project_id)
    REFERENCES projects(id) ON DELETE SET NULL;

-- Manage the updated_at column
SELECT updated_at('projects');

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON projects TO application_user;
GRANT USAGE, SELECT ON projects_id_seq TO application_user;

-- Give access to the readonly user
GRANT SELECT, INSERT, UPDATE, DELETE ON projects TO application_readonly;
GRANT USAGE, SELECT ON projects_id_seq TO application_readonly;

-- migrate:down
ALTER TABLE conversations DROP CONSTRAINT FK_project;
ALTER TABLE conversations DROP COLUMN project_id;

DROP INDEX projects_dataset_id_idx;
DROP TABLE projects;

ALTER TABLE datasets DROP COLUMN is_project;
