-- migrate:up
CREATE SCHEMA IF NOT EXISTS context;

CREATE TABLE context.skills (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL REFERENCES iam.teams(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    visibility visibility NOT NULL,
    created_by INT NOT NULL REFERENCES iam.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE context.skill_files (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id INT NOT NULL REFERENCES context.skills(id) ON DELETE CASCADE,
    object_id INT NOT NULL REFERENCES storage.objects(id) ON DELETE CASCADE,
    relative_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(skill_id, relative_path)
);

SELECT updated_at('context.skills');

GRANT USAGE ON SCHEMA context TO application_user;
GRANT USAGE ON SCHEMA context TO application_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON context.skills, context.skill_files TO application_user;
GRANT USAGE, SELECT ON context.skills_id_seq, context.skill_files_id_seq TO application_user;
GRANT SELECT ON context.skills, context.skill_files TO application_readonly;
GRANT SELECT ON context.skills_id_seq, context.skill_files_id_seq TO application_readonly;

-- migrate:down
DROP TABLE IF EXISTS context.skill_files;
DROP TABLE IF EXISTS context.skills;
DROP SCHEMA IF EXISTS context;
