-- migrate:up
CREATE TABLE providers (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    svg_logo TEXT NOT NULL,
    default_model_name VARCHAR,
    default_model_display_name VARCHAR,
    default_model_context_size INT NOT NULL DEFAULT 0,
    default_model_description TEXT NOT NULL DEFAULT '',
    base_url VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Manage the updated_at column
SELECT updated_at('providers');

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON providers TO application_user;
GRANT USAGE, SELECT ON providers_id_seq TO application_user;

-- Give access to the readonly user
GRANT SELECT ON providers TO application_readonly;
GRANT SELECT ON providers_id_seq TO application_readonly;

-- migrate:down
DROP TABLE providers;
