-- migrate:up
CREATE SCHEMA projects;

GRANT USAGE ON SCHEMA projects TO application_user;
GRANT USAGE ON SCHEMA projects TO application_readonly;

-- Remove conversations which belonged to assistants before deleting their prompts.
DELETE FROM llm.conversations
WHERE id IN (
    SELECT DISTINCT c.conversation_id
    FROM llm.chats c
    JOIN assistants.prompts p ON p.id = c.prompt_id
    WHERE p.prompt_type = 'Assistant'
);

DELETE FROM storage.objects
WHERE id IN (
    SELECT image_icon_object_id
    FROM assistants.prompts
    WHERE prompt_type = 'Assistant'
      AND image_icon_object_id IS NOT NULL
);

DELETE FROM assistants.prompts WHERE prompt_type = 'Assistant';

ALTER TABLE assistants.prompts
    DROP COLUMN prompt_type,
    DROP COLUMN category_id,
    DROP COLUMN image_icon_object_id,
    DROP COLUMN max_chunks;

DROP TABLE assistants.categories;
DROP TYPE prompt_type;

ALTER TABLE assistants.prompts SET SCHEMA model_registry;
ALTER TABLE assistants.prompt_dataset SET SCHEMA model_registry;
ALTER TABLE assistants.projects SET SCHEMA projects;

DROP SCHEMA assistants;

DELETE FROM iam.roles_permissions WHERE permission = 'ViewPrompts';

CREATE TYPE permission_without_assistants AS ENUM (
    'InvitePeopleToTeam',
    'ViewCurrentTeam',
    'ManagePipelines',
    'ViewDatasets',
    'ManageDatasets',
    'CreateApiKeys',
    'ViewAuditTrail',
    'SetupModels',
    'DeleteChat',
    'SetCompanyVisibility',
    'ViewSystemPrompt',
    'ViewIntegrations',
    'ManageIntegrations',
    'ViewChats',
    'ManageDocumentPipelines',
    'ManageMcpKeys',
    'ViewChatHistory',
    'ManageProjects'
);

ALTER TABLE iam.roles_permissions
    ALTER COLUMN permission TYPE permission_without_assistants
    USING (
        CASE permission::text
            WHEN 'MakeAssistantPublic' THEN 'SetCompanyVisibility'
            ELSE permission::text
        END
    )::permission_without_assistants;

DROP TYPE permission;
ALTER TYPE permission_without_assistants RENAME TO permission;

DELETE FROM ops.translations
WHERE key IN (
    'i18n.ai_assistants',
    'i18n.prompts',
    'i18n.assistants',
    'i18n.assistant'
);


-- migrate:down
CREATE SCHEMA assistants;

GRANT USAGE ON SCHEMA assistants TO application_user;
GRANT USAGE ON SCHEMA assistants TO application_readonly;

ALTER TABLE model_registry.prompts SET SCHEMA assistants;
ALTER TABLE model_registry.prompt_dataset SET SCHEMA assistants;
ALTER TABLE projects.projects SET SCHEMA assistants;
DROP SCHEMA projects;

CREATE TYPE prompt_type AS ENUM ('Assistant', 'Model');

ALTER TABLE assistants.prompts
    ADD COLUMN prompt_type prompt_type NOT NULL DEFAULT 'Model',
    ADD COLUMN category_id INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN image_icon_object_id INTEGER,
    ADD COLUMN max_chunks INTEGER NOT NULL DEFAULT 10;

CREATE TABLE assistants.categories (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

GRANT SELECT, INSERT, UPDATE, DELETE ON assistants.categories TO application_user;
GRANT USAGE, SELECT ON assistants.categories_id_seq TO application_user;
GRANT SELECT ON assistants.categories TO application_readonly;
GRANT SELECT ON assistants.categories_id_seq TO application_readonly;

CREATE TYPE permission_with_assistants AS ENUM (
    'InvitePeopleToTeam', 'ViewCurrentTeam', 'ViewPrompts', 'ManagePipelines',
    'ViewDatasets', 'ManageDatasets', 'CreateApiKeys', 'ViewAuditTrail',
    'SetupModels', 'DeleteChat', 'MakeAssistantPublic', 'ViewSystemPrompt',
    'ViewIntegrations', 'ManageIntegrations', 'ViewChats',
    'ManageDocumentPipelines', 'ManageMcpKeys', 'ViewChatHistory', 'ManageProjects'
);

ALTER TABLE iam.roles_permissions
    ALTER COLUMN permission TYPE permission_with_assistants
    USING (
        CASE permission::text
            WHEN 'SetCompanyVisibility' THEN 'MakeAssistantPublic'
            ELSE permission::text
        END
    )::permission_with_assistants;

DROP TYPE permission;
ALTER TYPE permission_with_assistants RENAME TO permission;
