-- migrate:up

CREATE TABLE llm.requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INT NOT NULL REFERENCES llm.chats(id) ON DELETE CASCADE,
    method TEXT NOT NULL,
    uri TEXT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX llm_requests_chat_id_idx ON llm.requests (chat_id);
CREATE INDEX llm_requests_id_desc_idx ON llm.requests (id DESC);

GRANT SELECT, INSERT ON llm.requests TO application_user;
GRANT USAGE, SELECT ON llm.requests_id_seq TO application_user;
GRANT SELECT ON llm.requests TO application_readonly;
GRANT SELECT ON llm.requests_id_seq TO application_readonly;

-- migrate:down

DROP TABLE llm.requests;
