apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.5.18
  
  # Enterprise Options
  # enterprise-key: EMAIL_US_FOR_A_KEY
  # enterprise-user: your_email@your_work_address.com
  # enterprise-expiry: Expiry date of your key (For trial users)

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:75ea6bab51359b78afdde708608ee70569f973b40df9304d81f88ac1be079603
  hash-bionicgpt-pipeline-job: sha256:28eb5035bc5335473026bab5910870e6b524338f11f524c8a83acd9ecf671fe4
  hash-bionicgpt-db-migrations: sha256:e945886b08070e5e4b997d2bfa210295bde69f46f3768e7af856a0953854f87e