apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.5.19
  
  # Enterprise Options
  # enterprise-key: EMAIL_US_FOR_A_KEY
  # enterprise-user: your_email@your_work_address.com
  # enterprise-expiry: Expiry date of your key (For trial users)

  # Use by Oauth2 proxy to know where to redirect and also keycloak (if installed)
  # to know how to set the openid configuration
  hostname-url: https://localhost

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:c30abe6be3b0743510b796656a6b60c33873040cc865463f389257a530db7716
  hash-bionicgpt-pipeline-job: sha256:7701aea2c65e31805f9ef2bf0dafa2b3debd85c2263d95f122ede0ea5e5967a1
  hash-bionicgpt-db-migrations: sha256:6c4e2c8e5044a118088ace2f880812f9437067986f4f8418e6e12c1575e88199