apiVersion: bionic-gpt.com/v1
kind: Bionic
metadata:
  name: bionic-gpt
  namespace: bionic-gpt 
spec:
  replicas: 1 
  version: 1.5.16
  
  # Enterprise Options
  # enterprise-key: EMAIL_US_FOR_A_KEY
  # enterprise-user: your_email@your_work_address.com
  # enterprise-expiry: Expiry date of your key (For trial users)

  # Image hashes to protect against supply chain attacks.
  hash-bionicgpt: sha256:0b11264a9256051644663118141d917d45ac1d41edfd5f45d7be3719c06c84af
  hash-bionicgpt-pipeline-job: sha256:7d3320d9928e70e7c28aada19d9c64c7afc81fe4827db7bc894d44ad6ad1cd9e
  hash-bionicgpt-db-migrations: sha256:f118c301fd3224a17fe0ade799ff02794c492b5394035174be9c18041f1eef93