{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://api.bitbucket.org/2.0"
    }
  ],
  "info": {
    "title": "Bitbucket",
    "description": "Manage Bitbucket workspaces, repositories, branches, pull requests, commits, and issues through the Bitbucket Cloud REST API.",
    "version": "2.0",
    "termsOfService": "https://www.atlassian.com/legal/customer-agreement",
    "contact": {
      "name": "Bitbucket Support",
      "url": "https://support.atlassian.com/bitbucket-cloud/",
      "email": "support@bitbucket.org"
    },
    "x-bionic-slug": "bitbucket",
    "x-bionic-source-url": "https://api.bitbucket.org/swagger.json",
    "x-logo": {
      "url": "data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+Qml0YnVja2V0PC90aXRsZT48cGF0aCBmaWxsPSIjMDA1MkNDIiBkPSJNLjc3OCAxLjIxM2EuNzY4Ljc2OCAwIDAwLS43NjguODkybDMuMjYzIDE5LjgxYy4wODQuNS41MTUuODY4IDEuMDIyLjg3M0gxOS45NWEuNzcyLjc3MiAwIDAwLjc3LS42NDZsMy4yNy0yMC4wM2EuNzY4Ljc2OCAwIDAwLS43NjgtLjg5MXpNMTQuNTIgMTUuNTNIOS41MjJMOC4xNyA4LjQ2Nmg3LjU2MXoiLz48L3N2Zz4="
    }
  },
  "paths": {
    "/addon": {
      "delete": {
        "tags": [
          "Addon"
        ],
        "description": "Deletes the application for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket Marketplace need not use this endpoint as\nupdates for those applications can be sent out via the\nUI of that section.\n\n```\n$ curl -X DELETE https://api.bitbucket.org/[...]",
        "summary": "Delete an app",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "operationId": "delete_addon"
      },
      "put": {
        "tags": [
          "Addon"
        ],
        "description": "Updates the application installation for the user.\n\nThis endpoint is intended to be used by Bitbucket Connect apps\nand only supports JWT authentication -- that is how Bitbucket\nidentifies the particular installation of the app. Developers\nwith applications registered in the \"Develop Apps\" section\nof Bitbucket need not use this endpoint as updates for those\napplications can be sent out via the UI of that section.\n\nPassing an empty body will update the installati[...]",
        "summary": "Update an installed app",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "operationId": "put_addon"
      }
    },
    "/addon/{addon_key}/client-key": {
      "get": {
        "tags": [
          "Addon"
        ],
        "description": "Get the client key of the Connect addon associated with a Forge app install via forgeAppId linkage.\n\nThis endpoint is part of the Connect -> Forge migration tooling. It is intended to be used by a Forge app\nusing `asApp().requestBitbucket()` only.\nPrerequisite: app developer needs to register the linkage between their Connect and Forge app by setting\n`forgeAppId` in the Connect addon descriptor to `app.id` from Forge app manifest, then update the installations.\nIf t[...]",
        "summary": "Get the client key of a Connect addon",
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:workspace:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2"
        ],
        "operationId": "get_addon_addon_key_client_key"
      }
    },
    "/hook_events": {
      "get": {
        "operationId": "list_hook_events",
        "summary": "Get a webhook resource",
        "description": "Returns the webhook resource or subject types on which webhooks can be registered.\nEach resource/subject type contains an `events` link that returns the paginated list of specific events each individual subject type can emit.\nThis endpoint is publicly accessible and does not require authentication or scopes.",
        "tags": [
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/hook_events/{subject_type}": {
      "get": {
        "operationId": "list_hook_events_for_resource",
        "summary": "List subscribable webhook types",
        "description": "Returns a paginated list of all valid webhook events for the specified entity.\n**The team and user webhooks are deprecated, and you should use workspace instead. For more information, see [the announcement](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/).**\nThis is public data that does not require any scopes or authentication.\nNOTE: The example response is a truncated response object for the `workspace` `subject_type`. We return the s[...]",
        "tags": [
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      }
    },
    "/repositories/{workspace}": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns a paginated list of all repositories owned by the specified\nworkspace.\n\nThe result can be narrowed down based on the authenticated user's role.\n\nE.g. with `?role=contributor`, only those repositories that the\nauthenticated user has write access to are returned (this includes any\nrepo the user is an admin on, as that implies write access).\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](/cloud/bitbucket/rest/[...]",
        "summary": "List repositories in a workspace",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace"
      }
    },
    "/repositories/{workspace}/{repo_slug}": {
      "delete": {
        "tags": [
          "Repositories"
        ],
        "description": "Deletes the repository. This is an irreversible operation.\n\nThis does not affect its forks.",
        "summary": "Delete a repository",
        "security": [
          {
            "oauth2": [
              "repository:delete"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "delete:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug"
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns the object describing this repository.",
        "summary": "Get a repository",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug"
      },
      "post": {
        "tags": [
          "Repositories"
        ],
        "description": "Creates a new repository.\n\nNote: In order to set the project for the newly created repository,\npass in either the project key or the project UUID as part of the\nrequest body as shown in the examples below:\n\n```\n$ curl -X POST -H \"Content-Type: application/json\" -d '{\n    \"scm\": \"git\",\n    \"project\": {\n        \"key\": \"MARS\"\n    }\n}' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding\n```\n\nor\n\n```\n$ curl -X POST -H \"Content-Type[...]",
        "summary": "Create a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug"
      },
      "put": {
        "tags": [
          "Repositories"
        ],
        "description": "Since this endpoint can be used to both update and to create a\nrepository, the request body depends on the intent.\n\n#### Creation\n\nSee the POST documentation for the repository endpoint for an example\nof the request body.\n\n#### Update\n\nNote: Changing the `name` of the repository will cause the location to\nbe changed. This is because the URL of the repo is derived from the\nname (a process called slugification). In such a scenario, it is\npossible for the reques[...]",
        "summary": "Update a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug"
      }
    },
    "/repositories/{workspace}/{repo_slug}/branch-restrictions": {
      "get": {
        "tags": [
          "Branch restrictions"
        ],
        "description": "Returns a paginated list of all branch restrictions on the\nrepository.",
        "summary": "List branch restrictions",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_branch_restrictions"
      },
      "post": {
        "tags": [
          "Branch restrictions"
        ],
        "description": "Creates a new branch restriction rule for a repository.\n\n`kind` describes what will be restricted. Allowed values include:\n`push`, `force`, `delete`, `restrict_merges`, `require_tasks_to_be_completed`,\n`require_approvals_to_merge`, `require_default_reviewer_approvals_to_merge`,\n`require_no_changes_requested`, `require_passing_builds_to_merge`, `require_commits_behind`,\n`reset_pullrequest_approvals_on_change`, `smart_reset_pullrequest_approvals`,\n`reset_pullrequest_[...]",
        "summary": "Create a branch restriction rule",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_branch_restrictions"
      }
    },
    "/repositories/{workspace}/{repo_slug}/branch-restrictions/{id}": {
      "delete": {
        "tags": [
          "Branch restrictions"
        ],
        "description": "Deletes an existing branch restriction rule.",
        "summary": "Delete a branch restriction rule",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_branch_restrictions_id"
      },
      "get": {
        "tags": [
          "Branch restrictions"
        ],
        "description": "Returns a specific branch restriction rule.",
        "summary": "Get a branch restriction rule",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_branch_restrictions_id"
      },
      "put": {
        "tags": [
          "Branch restrictions"
        ],
        "description": "Updates an existing branch restriction rule.\n\nFields not present in the request body are ignored.\n\nSee [`POST`](/cloud/bitbucket/rest/api-group-branch-restrictions/#api-repositories-workspace-repo-slug-branch-restrictions-post) for details.",
        "summary": "Update a branch restriction rule",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_branch_restrictions_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/branching-model": {
      "get": {
        "tags": [
          "Branching model"
        ],
        "description": "Return the branching model as applied to the repository. This view is\nread-only. The branching model settings can be changed using the\n[settings](#api-repositories-workspace-repo-slug-branching-model-settings-get) API.\n\nThe returned object:\n\n1. Always has a `development` property. `development.branch` contains\n   the actual repository branch object that is considered to be the\n   `development` branch. `development.branch` will not be present\n   if it does not exi[...]",
        "summary": "Get the branching model for a repository",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_branching_model"
      }
    },
    "/repositories/{workspace}/{repo_slug}/branching-model/settings": {
      "get": {
        "tags": [
          "Branching model"
        ],
        "description": "Return the branching model configuration for a repository. The returned\nobject:\n\n1. Always has a `development` property for the development branch.\n2. Always a `production` property for the production branch. The\n   production branch can be disabled.\n3. The `branch_types` contains all the branch types.\n4. `default_branch_deletion` indicates whether branches will be\n    deleted by default on merge.\n\nThis is the raw configuration for the branching model. A client\[...]",
        "summary": "Get the branching model config for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_branching_model_settings"
      },
      "put": {
        "tags": [
          "Branching model"
        ],
        "description": "Update the branching model configuration for a repository.\n\nThe `development` branch can be configured to a specific branch or to\ntrack the main branch. When set to a specific branch it must\ncurrently exist. Only the passed properties will be updated. The\nproperties not passed will be left unchanged. A request without a\n`development` property will leave the development branch unchanged.\n\nIt is possible for the `development` branch to be invalid. This\nhappens when[...]",
        "summary": "Update the branching model config for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_branching_model_settings"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Returns the specified commit.",
        "summary": "Get a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commit_commit"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/approve": {
      "delete": {
        "tags": [
          "Commits"
        ],
        "description": "Redact the authenticated user's approval of the specified commit.\n\nThis operation is only available to users that have explicit access to\nthe repository. In contrast, just the fact that a repository is\npublicly accessible to users does not give them the ability to approve\ncommits.",
        "summary": "Unapprove a commit",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_commit_commit_approve"
      },
      "post": {
        "tags": [
          "Commits"
        ],
        "description": "Approve the specified commit as the authenticated user.\n\nThis operation is only available to users that have explicit access to\nthe repository. In contrast, just the fact that a repository is\npublicly accessible to users does not give them the ability to approve\ncommits.",
        "summary": "Approve a commit",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket",
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_commit_commit_approve"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/comments": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Returns the commit's comments.\n\nThis includes both global and inline comments.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.",
        "summary": "List a commit's comments",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commit_commit_comments"
      },
      "post": {
        "tags": [
          "Commits"
        ],
        "description": "Creates new comment on the specified commit.\n\nTo post a reply to an existing comment, include the `parent.id` field:\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/db9ba1e031d07a02603eae0e559a7adc010257fc/comments/ \\\n  -X POST -u evzijst \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\": {\"raw\": \"One more thing!\"},\n       \"parent\": {\"id\": 5728901}}'\n```",
        "summary": "Create comment for a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_commit_commit_comments"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/comments/{comment_id}": {
      "delete": {
        "tags": [
          "Commits"
        ],
        "description": "Deletes the specified commit comment.\n\nNote that deleting comments that have visible replies that point to\nthem will not really delete the resource. This is to retain the integrity\nof the original comment tree. Instead, the `deleted` element is set to\n`true` and the content is blanked out. The comment will continue to be\nreturned by the collections and self endpoints.",
        "summary": "Delete a commit comment",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_commit_commit_comments_comment_id"
      },
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Returns the specified commit comment.",
        "summary": "Get a commit comment",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commit_commit_comments_comment_id"
      },
      "put": {
        "tags": [
          "Commits"
        ],
        "description": "Used to update the contents of a comment. Only the content of the comment can be updated.\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/commit/7f71b5/comments/5728901 \\\n  -X PUT -u evzijst \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"content\": {\"raw\": \"One more thing!\"}'\n```",
        "summary": "Update a commit comment",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_commit_commit_comments_comment_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/properties/{app_key}/{property_name}": {
      "put": {
        "deprecated": true,
        "operationId": "updateCommitHostedPropertyValue",
        "summary": "Update a commit application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nUpdate an [application property](/cloud/bitbucket/application-properties/) value stored against a commit.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      },
      "delete": {
        "deprecated": true,
        "operationId": "deleteCommitHostedPropertyValue",
        "summary": "Delete a commit application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nDelete an [application property](/cloud/bitbucket/application-properties/) value stored against a commit.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "deprecated": true,
        "operationId": "getCommitHostedPropertyValue",
        "summary": "Get a commit application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nRetrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a commit.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:workspace:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/pullrequests": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "summary": "List pull requests that contain a commit",
        "description": "Returns a paginated list of all pull requests as part of which this commit was reviewed. Pull Request Commit Links app must be installed first before using this API; installation automatically occurs when 'Go to pull request' is clicked from the web interface for a commit's details.",
        "operationId": "getPullrequestsForCommit",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports": {
      "get": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Returns a paginated list of Reports linked to this commit.",
        "summary": "List reports",
        "operationId": "getReportsForCommit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}": {
      "put": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Creates or updates a report for the specified commit.\nTo upload a report, make sure to generate an ID that is unique across all reports for that commit. If you want to use an existing id from your own system, we recommend prefixing it with your system's name to avoid collisions, for example, mySystem-001.\n\n### Sample cURL request:\n```\ncurl --request PUT 'https://api.bitbucket.org/2.0/repositories/<username>/<reposity-name>/commit/<commit-hash>/reports/mysystem-001' \[...]",
        "operationId": "createOrUpdateReport",
        "summary": "Create or update a report",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "get": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Returns a single Report matching the provided ID.",
        "summary": "Get a report",
        "operationId": "getReport",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Deletes a single Report matching the provided ID.",
        "summary": "Delete a report",
        "operationId": "deleteReport",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations": {
      "get": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Returns a paginated list of Annotations for a specified report.",
        "summary": "List annotations",
        "operationId": "getAnnotationsForReport",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Bulk upload of annotations.\nAnnotations are individual findings that have been identified as part of a report, for example, a line of code that represents a vulnerability. These annotations can be attached to a specific file and even a specific line in that file, however, that is optional. Annotations are not mandatory and a report can contain up to 1000 annotations.\n\nAdd the annotations you want to upload as objects in a JSON array and make sure each annotation has th[...]",
        "operationId": "bulkCreateOrUpdateAnnotations",
        "summary": "Bulk create or update annotations",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/reports/{reportId}/annotations/{annotationId}": {
      "get": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Returns a single Annotation matching the provided ID.",
        "summary": "Get an annotation",
        "operationId": "getAnnotation",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Creates or updates an individual annotation for the specified report.\nAnnotations are individual findings that have been identified as part of a report, for example, a line of code that represents a vulnerability. These annotations can be attached to a specific file and even a specific line in that file, however, that is optional. Annotations are not mandatory and a report can contain up to 1000 annotations.\n\nJust as reports, annotation needs to be uploaded with a uniq[...]",
        "operationId": "createOrUpdateAnnotation",
        "summary": "Create or update an annotation",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Reports",
          "Commits"
        ],
        "description": "Deletes a single Annotation matching the provided ID.",
        "summary": "Delete an annotation",
        "operationId": "deleteAnnotation",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/statuses": {
      "get": {
        "tags": [
          "Commit statuses"
        ],
        "description": "Returns all statuses (e.g. build results) for a specific commit.",
        "summary": "List commit statuses for a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commit_commit_statuses"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/statuses/build": {
      "post": {
        "tags": [
          "Commit statuses"
        ],
        "description": "Creates a new build status against the specified commit.\n\nIf the specified key already exists, the existing status object will\nbe overwritten.\n\nExample:\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/my-workspace/my-repo/commit/e10dae226959c2194f2b07b077c07762d93821cf/statuses/build/           -X POST -u jdoe -H 'Content-Type: application/json'           -d '{\n    \"key\": \"MY-BUILD\",\n    \"state\": \"SUCCESSFUL\",\n    \"description\": \"42 tests passed[...]",
        "summary": "Create a build status for a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_commit_commit_statuses_build"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}/statuses/build/{key}": {
      "get": {
        "tags": [
          "Commit statuses"
        ],
        "description": "Returns the specified build status for a commit.",
        "summary": "Get a build status for a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commit_commit_statuses_build_key"
      },
      "put": {
        "tags": [
          "Commit statuses"
        ],
        "description": "Used to update the current status of a build status object on the\nspecific commit.\n\nThis operation can also be used to change other properties of the\nbuild status:\n\n* `state`\n* `name`\n* `description`\n* `url`\n* `refname`\n\nThe `key` cannot be changed.",
        "summary": "Update a build status for a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_commit_commit_statuses_build_key"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commits": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "These are the repository's commits. They are paginated and returned\nin reverse chronological order, similar to the output of `git log`.\nLike these tools, the DAG can be filtered.\n\n#### GET /repositories/{workspace}/{repo_slug}/commits/\n\nReturns all commits in the repo in topological order (newest commit\nfirst). All branches and tags are included (similar to\n`git log --all`).\n\n#### GET /repositories/{workspace}/{repo_slug}/commits/?exclude=master\n\nReturns all c[...]",
        "summary": "List commits",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commits"
      },
      "post": {
        "tags": [
          "Commits"
        ],
        "description": "Identical to `GET /repositories/{workspace}/{repo_slug}/commits`,\nexcept that POST allows clients to place the include and exclude\nparameters in the request body to avoid URL length issues.\n\n**Note that this resource does NOT support new commit creation.**",
        "summary": "List commits with include/exclude",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_commits"
      }
    },
    "/repositories/{workspace}/{repo_slug}/commits/{revision}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "These are the repository's commits. They are paginated and returned\nin reverse chronological order, similar to the output of `git log`.\nLike these tools, the DAG can be filtered.\n\n#### GET /repositories/{workspace}/{repo_slug}/commits/master\n\nReturns all commits on ref `master` (similar to `git log master`).\n\n#### GET /repositories/{workspace}/{repo_slug}/commits/dev?include=foo&exclude=master\n\nReturns all commits on ref `dev` or `foo`, except those that are rea[...]",
        "summary": "List commits for revision",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_commits_revision"
      },
      "post": {
        "tags": [
          "Commits"
        ],
        "description": "Identical to `GET /repositories/{workspace}/{repo_slug}/commits/{revision}`,\nexcept that POST allows clients to place the include and exclude\nparameters in the request body to avoid URL length issues.\n\n**Note that this resource does NOT support new commit creation.**",
        "summary": "List commits for revision using include/exclude",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_commits_revision"
      }
    },
    "/repositories/{workspace}/{repo_slug}/default-reviewers": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns the repository's default reviewers.\n\nThese are the users that are automatically added as reviewers on every\nnew pull request that is created. To obtain the repository's default reviewers\nas well as the default reviewers inherited from the project, use the\n[effective-default-reveiwers](#api-repositories-workspace-repo-slug-effective-default-reviewers-get) endpoint.",
        "summary": "List default reviewers",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_default_reviewers"
      }
    },
    "/repositories/{workspace}/{repo_slug}/default-reviewers/{target_username}": {
      "delete": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Removes a default reviewer from the repository.",
        "summary": "Remove a user from the default reviewers",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_default_reviewers_target_username"
      },
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns the specified reviewer.\n\nThis can be used to test whether a user is among the repository's\ndefault reviewers list. A 404 indicates that that specified user is not\na default reviewer.",
        "summary": "Get a default reviewer",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_default_reviewers_target_username"
      },
      "put": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Adds the specified user to the repository's list of default\nreviewers.\n\nThis method is idempotent. Adding a user a second time has no effect.",
        "summary": "Add a user to the default reviewers",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_default_reviewers_target_username"
      }
    },
    "/repositories/{workspace}/{repo_slug}/deploy-keys": {
      "get": {
        "tags": [
          "Deployments"
        ],
        "description": "Returns all deploy-keys belonging to a repository.",
        "summary": "List repository deploy keys",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_deploy_keys"
      },
      "post": {
        "tags": [
          "Deployments"
        ],
        "description": "Create a new deploy key in a repository. Note: If authenticating a deploy key\nwith an OAuth consumer, any changes to the OAuth consumer will subsequently\ninvalidate the deploy key.\n\n\nExample:\n```\n$ curl -X POST \\\n-H \"Authorization <auth header>\" \\\n-H \"Content-type: application/json\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys -d \\\n'{\n    \"key\": \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyT[...]",
        "summary": "Add a repository deploy key",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "write:ssh-key:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_deploy_keys"
      }
    },
    "/repositories/{workspace}/{repo_slug}/deploy-keys/{key_id}": {
      "delete": {
        "tags": [
          "Deployments"
        ],
        "description": "This deletes a deploy key from a repository.",
        "summary": "Delete a repository deploy key",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "delete:ssh-key:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_deploy_keys_key_id"
      },
      "get": {
        "tags": [
          "Deployments"
        ],
        "description": "Returns the deploy key belonging to a specific key.",
        "summary": "Get a repository deploy key",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_deploy_keys_key_id"
      },
      "put": {
        "tags": [
          "Deployments"
        ],
        "description": "Update an existing deploy key in a repository.\n\nThe same key needs to be passed in but the comment and label can change.\n\nExample:\n```\n$ curl -X PUT \\\n-H \"Authorization <auth header>\" \\\n-H \"Content-type: application/json\" \\\nhttps://api.bitbucket.org/2.0/repositories/mleu/test/deploy-keys/1234 -d \\\n'{\n    \"label\": \"newlabel\",\n    \"key\": \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAK/b1cHHDr/TEV1JGQl+WjCwStKG6Bhrv0rFpEsYlyTBm1fzN0VOJJYn4ZOPCPJwqse6fGb[...]",
        "summary": "Update a repository deploy key",
        "security": [
          {
            "oauth2": [
              "repository",
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "write:ssh-key:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_deploy_keys_key_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments": {
      "get": {
        "tags": [
          "Deployments"
        ],
        "description": "Find deployments",
        "summary": "List deployments",
        "operationId": "getDeploymentsForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments/{deployment_uuid}": {
      "get": {
        "tags": [
          "Deployments"
        ],
        "description": "Retrieve a deployment",
        "summary": "Get a deployment",
        "operationId": "getDeploymentForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments_config/environments/{environment_uuid}/variables": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "description": "Find deployment environment level variables.",
        "summary": "List variables for an environment",
        "operationId": "getDeploymentVariables",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Pipelines"
        ],
        "description": "Create a deployment environment level variable.",
        "summary": "Create a variable for an environment",
        "operationId": "createDeploymentVariable",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/deployments_config/environments/{environment_uuid}/variables/{variable_uuid}": {
      "put": {
        "tags": [
          "Pipelines"
        ],
        "description": "Update a deployment environment level variable.",
        "summary": "Update a variable for an environment",
        "operationId": "updateDeploymentVariable",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "description": "Delete a deployment environment level variable.",
        "summary": "Delete a variable for an environment",
        "operationId": "deleteDeploymentVariable",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/diff/{spec}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Produces a raw git-style diff.\n\n#### Single commit spec\n\nIf the `spec` argument to this API is a single commit, the diff is\nproduced against the first parent of the specified commit.\n\n#### Two commit spec\n\nTwo commits separated by `..` may be provided as the `spec`, e.g.,\n`3a8b42..9ff173`. When two commits are provided and the `topic` query\nparameter is true, this API produces a 2-way three dot diff.\nThis is the diff between source commit and the merge base of[...]",
        "summary": "Compare two commits",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_diff_spec"
      }
    },
    "/repositories/{workspace}/{repo_slug}/diffstat/{spec}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Produces a response in JSON format with a record for every path\nmodified, including information on the type of the change and the\nnumber of lines added and removed.\n\n#### Single commit spec\n\nIf the `spec` argument to this API is a single commit, the diff is\nproduced against the first parent of the specified commit.\n\n#### Two commit spec\n\nTwo commits separated by `..` may be provided as the `spec`, e.g.,\n`3a8b42..9ff173`. When two commits are provided and the `[...]",
        "summary": "Compare two commit diff stats",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_diffstat_spec"
      }
    },
    "/repositories/{workspace}/{repo_slug}/downloads": {
      "get": {
        "tags": [
          "Downloads"
        ],
        "description": "Returns a list of download links associated with the repository.",
        "summary": "List download artifacts",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_downloads"
      },
      "post": {
        "tags": [
          "Downloads"
        ],
        "description": "Upload new download artifacts.\n\nTo upload files, perform a `multipart/form-data` POST containing one\nor more `files` fields:\n\n    $ echo Hello World > hello.txt\n    $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads -F files=@hello.txt\n\nWhen a file is uploaded with the same name as an existing artifact,\nthen the existing file will be replaced.",
        "summary": "Upload a download artifact",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_downloads"
      }
    },
    "/repositories/{workspace}/{repo_slug}/downloads/{filename}": {
      "delete": {
        "tags": [
          "Downloads"
        ],
        "description": "Deletes the specified download artifact from the repository.",
        "summary": "Delete a download artifact",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_downloads_filename"
      },
      "get": {
        "tags": [
          "Downloads"
        ],
        "description": "Return a redirect to the contents of a download artifact.\n\nThis endpoint returns the actual file contents and not the artifact's\nmetadata.\n\n    $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt\n    Hello World",
        "summary": "Get a download artifact link",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_downloads_filename"
      }
    },
    "/repositories/{workspace}/{repo_slug}/effective-branching-model": {
      "get": {
        "tags": [
          "Branching model"
        ],
        "description": "",
        "summary": "Get the effective, or currently applied, branching model for a repository",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_effective_branching_model"
      }
    },
    "/repositories/{workspace}/{repo_slug}/effective-default-reviewers": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns the repository's effective default reviewers. This includes both default\nreviewers defined at the repository level as well as those inherited from its project.\n\nThese are the users that are automatically added as reviewers on every\nnew pull request that is created.",
        "summary": "List effective default reviewers",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_effective_default_reviewers"
      }
    },
    "/repositories/{workspace}/{repo_slug}/environments": {
      "get": {
        "tags": [
          "Deployments"
        ],
        "description": "Find environments",
        "summary": "List environments",
        "operationId": "getEnvironmentsForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Deployments"
        ],
        "description": "Create an environment.",
        "summary": "Create an environment",
        "operationId": "createEnvironment",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/environments/{environment_uuid}": {
      "get": {
        "tags": [
          "Deployments"
        ],
        "summary": "Get an environment",
        "description": "Retrieve an environment",
        "operationId": "getEnvironmentForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Deployments"
        ],
        "description": "Delete an environment",
        "summary": "Delete an environment",
        "operationId": "deleteEnvironmentForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/environments/{environment_uuid}/changes": {
      "post": {
        "tags": [
          "Deployments"
        ],
        "description": "Update an environment",
        "summary": "Update an environment",
        "operationId": "updateEnvironmentForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/file-conflicts/{spec}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Get file conflicts for a commit spec",
        "summary": "Get file conflicts for a commit spec",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_file_conflicts_spec"
      }
    },
    "/repositories/{workspace}/{repo_slug}/filehistory/{commit}/{path}": {
      "get": {
        "tags": [
          "Source",
          "Repositories"
        ],
        "description": "Returns a paginated list of commits that modified the specified file.\n\nCommits are returned in reverse chronological order. This is roughly\nequivalent to the following commands:\n\n    $ git log --follow --date-order <sha> <path>\n\nBy default, Bitbucket will follow renames and the path name in the\nreturned entries reflects that. This can be turned off using the\n`?renames=false` query parameter.\n\nResults are returned in descending chronological order by default, an[...]",
        "summary": "List commits that modified a file",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_filehistory_commit_path"
      }
    },
    "/repositories/{workspace}/{repo_slug}/forks": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns a paginated list of all the forks of the specified\nrepository.",
        "summary": "List repository forks",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_forks"
      },
      "post": {
        "tags": [
          "Repositories"
        ],
        "description": "Creates a new fork of the specified repository.\n\n#### Forking a repository\n\nTo create a fork, specify the workspace explicitly as part of the\nrequest body:\n\n```\n$ curl -X POST -u jdoe https://api.bitbucket.org/2.0/repositories/atlassian/bbql/forks \\\n  -H 'Content-Type: application/json' -d '{\n    \"name\": \"bbql_fork\",\n    \"workspace\": {\n      \"slug\": \"atlassian\"\n    }\n}'\n```\n\nTo fork a repository into the same workspace, also specify a new `name[...]",
        "summary": "Fork a repository",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket",
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_forks"
      }
    },
    "/repositories/{workspace}/{repo_slug}/hooks": {
      "get": {
        "operationId": "list_repository_hooks",
        "summary": "List webhooks for a repository",
        "description": "Returns a paginated list of webhooks installed on this repository.\n",
        "tags": [
          "Repositories",
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:webhook:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ]
      },
      "post": {
        "operationId": "create_repository_hook",
        "summary": "Create a webhook for a repository",
        "description": "Creates a new webhook on the specified repository.\n\nWorkspace webhooks are fired for events from all repositories\ncontained by that workspace.\n\nExample:\n```\n$ curl -X POST -u credentials -H 'Content-Type: application/json'\n  https://api.bitbucket.org/2.0/workspaces/my-workspace/hooks\n  -d '\n    {\n      \"description\": \"Webhook Description\",\n      \"url\": \"https://example.com/\",\n      \"active\": true,\n      \"secret\": \"this is a really bad secret\",\[...]",
        "tags": [
          "Repositories",
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:webhook:bitbucket",
              "write:webhook:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/hooks/{uid}": {
      "get": {
        "operationId": "get_repository_hook",
        "summary": "Get a webhook for a repository",
        "description": "Returns the webhook with the specified id installed on the\nspecified repository.\n",
        "tags": [
          "Repositories",
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:webhook:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ]
      },
      "put": {
        "operationId": "update_repository_hook",
        "summary": "Update a webhook for a repository",
        "description": "Updates the specified webhook subscription.\n\nThe following properties can be mutated:\n\n* `description`\n* `url`\n* `secret`\n* `active`\n* `events`\n\nThe hook's secret is used as a key to generate the HMAC hex digest\nsent in the `X-Hub-Signature` header at delivery time. This\nsignature is only generated when the hook has a secret.\n\nSet the hook's secret by passing the new value in the `secret`\nfield. Passing a `null` value in the `secret` field will remove\nthe [...]",
        "tags": [
          "Repositories",
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:webhook:bitbucket",
              "write:webhook:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ]
      },
      "delete": {
        "operationId": "delete_repository_hook",
        "summary": "Delete a webhook for a repository",
        "description": "Deletes the specified webhook subscription from the given\nrepository.\n",
        "tags": [
          "Repositories",
          "Webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "webhook"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "delete:webhook:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/merge-base/{revspec}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Returns the best common ancestor between two commits, specified in a revspec\nof 2 commits (e.g. 3a8b42..9ff173).\n\nIf more than one best common ancestor exists, only one will be returned. It is\nunspecified which will be returned.",
        "summary": "Get the common ancestor between two commits",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_merge_base_revspec"
      }
    },
    "/repositories/{workspace}/{repo_slug}/override-settings": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "",
        "summary": "Retrieve the inheritance state for repository settings",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_override_settings"
      },
      "put": {
        "tags": [
          "Repositories"
        ],
        "description": "",
        "summary": "Set the inheritance state for repository settings\n                ",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_override_settings"
      }
    },
    "/repositories/{workspace}/{repo_slug}/patch/{spec}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Produces a raw patch for a single commit (diffed against its first\nparent), or a patch-series for a revspec of 2 commits (e.g.\n`3a8b42..9ff173` where the first commit represents the source and the\nsecond commit the destination).\n\nIn case of the latter (diffing a revspec), a patch series is returned\nfor the commits on the source branch (`3a8b42` and its ancestors in\nour example).\n\nWhile similar to diffs, patches:\n\n* Have a commit header (username, commit message[...]",
        "summary": "Get a patch for two commits",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_patch_spec"
      }
    },
    "/repositories/{workspace}/{repo_slug}/permissions-config/groups": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns a paginated list of explicit group permissions for the given repository.\nThis endpoint does not support BBQL features.",
        "summary": "List explicit group permissions for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_permissions_config_groups"
      }
    },
    "/repositories/{workspace}/{repo_slug}/permissions-config/groups/{group_slug}": {
      "delete": {
        "tags": [
          "Repositories"
        ],
        "description": "Deletes the repository group permission between the requested repository and group, if one exists.\n\nOnly users with admin permission for the repository may access this resource.\n\nThe only authentication method supported for this endpoint is via app passwords.",
        "summary": "Delete an explicit group permission for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "delete:permission:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_permissions_config_groups_group_slug"
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns the group permission for a given group slug and repository\n\nOnly users with admin permission for the repository may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`\n* `none`",
        "summary": "Get an explicit group permission for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_permissions_config_groups_group_slug"
      },
      "put": {
        "tags": [
          "Repositories"
        ],
        "description": "Updates the group permission, or grants a new permission if one does not already exist.\n\nOnly users with admin permission for the repository may access this resource.\n\nThe only authentication method supported for this endpoint is via app passwords.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`",
        "summary": "Update an explicit group permission for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "write:permission:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_permissions_config_groups_group_slug"
      }
    },
    "/repositories/{workspace}/{repo_slug}/permissions-config/users": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns a paginated list of explicit user permissions for the given repository.\nThis endpoint does not support BBQL features.",
        "summary": "List explicit user permissions for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_permissions_config_users"
      }
    },
    "/repositories/{workspace}/{repo_slug}/permissions-config/users/{selected_user_id}": {
      "delete": {
        "tags": [
          "Repositories"
        ],
        "description": "Deletes the repository user permission between the requested repository and user, if one exists.\n\nOnly users with admin permission for the repository may access this resource.\n\nThe only authentication method for this endpoint is via app passwords.",
        "summary": "Delete an explicit user permission for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "delete:permission:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_permissions_config_users_selected_user_id"
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns the explicit user permission for a given user and repository.\n\nOnly users with admin permission for the repository may access this resource.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`\n* `none`",
        "summary": "Get an explicit user permission for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_permissions_config_users_selected_user_id"
      },
      "put": {
        "tags": [
          "Repositories"
        ],
        "description": "Updates the explicit user permission for a given user and repository. The selected user must be a member of\nthe workspace, and cannot be the workspace owner.\nOnly users with admin permission for the repository may access this resource.\n\nThe only authentication method for this endpoint is via app passwords.\n\nPermissions can be:\n\n* `admin`\n* `write`\n* `read`",
        "summary": "Update an explicit user permission for a repository",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket",
              "write:permission:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_permissions_config_users_selected_user_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List pipelines",
        "description": "Find pipelines in a repository.\n\nNote that unlike other endpoints in the Bitbucket API, this endpoint utilizes query parameters to allow filtering\nand sorting of returned results. See [query parameters](#api-repositories-workspace-repo-slug-pipelines-get-request-Query%20parameters)\nfor specific details.\n",
        "operationId": "getPipelinesForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Run a pipeline",
        "description": "Endpoint to create and initiate a pipeline.\nThere are a number of different options to initiate a pipeline, where the payload of the request will determine which type of pipeline will be instantiated.\n\n## Trigger a pipeline for a branch\n\nOne way to trigger pipelines is by specifying the branch for which you want to trigger a pipeline.\nThe specified branch will be used to determine which pipeline definition from the `bitbucket-pipelines.yml` file will be applied to i[...]",
        "operationId": "createPipelineForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket",
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/caches": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List caches",
        "description": "Retrieve the repository pipelines caches.",
        "operationId": "getRepositoryPipelineCaches",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete caches",
        "description": "Delete repository cache versions by name.",
        "operationId": "deleteRepositoryPipelineCaches",
        "security": [
          {
            "oauth2": [
              "pipeline:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/caches/{cache_uuid}": {
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete a cache",
        "description": "Delete a repository cache.",
        "operationId": "deleteRepositoryPipelineCache",
        "security": [
          {
            "oauth2": [
              "pipeline:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/caches/{cache_uuid}/content-uri": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get cache content URI",
        "description": "Retrieve the URI of the content of the specified cache.",
        "operationId": "getRepositoryPipelineCacheContentURI",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/runners": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get repository runners",
        "description": "Retrieve repository runners.",
        "operationId": "getRepositoryRunners",
        "security": [
          {
            "oauth2": [
              "runner"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:runner:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Create repository runner",
        "description": "Create repository runner.",
        "operationId": "createRepositoryRunner",
        "security": [
          {
            "oauth2": [
              "runner:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:runner:bitbucket",
              "read:runner:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines-config/runners/{runner_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get repository runner",
        "description": "Retrieve repository runner by uuid.",
        "operationId": "getRepositoryRunner",
        "security": [
          {
            "oauth2": [
              "runner"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:runner:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update repository runner",
        "description": "Update repository runner.",
        "operationId": "updateRepositoryRunner",
        "security": [
          {
            "oauth2": [
              "runner:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:runner:bitbucket",
              "write:runner:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete repository runner",
        "description": "Delete repository runner by uuid.",
        "operationId": "deleteRepositoryRunner",
        "security": [
          {
            "oauth2": [
              "runner:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:runner:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get a pipeline",
        "description": "Retrieve a specified pipeline",
        "operationId": "getPipelineForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List steps for a pipeline",
        "description": "Find steps for the given pipeline.",
        "operationId": "getPipelineStepsForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get a step of a pipeline",
        "description": "Retrieve a given step of a pipeline.",
        "operationId": "getPipelineStepForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/log": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get log file for a step",
        "description": "Retrieve the log file for a given step of a pipeline.\n\nThis endpoint supports (and encourages!) the use of [HTTP Range requests](https://tools.ietf.org/html/rfc7233) to deal with potentially very large log files.",
        "operationId": "getPipelineStepLogForRepository",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/logs/{log_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get the logs for the build container or a service container for a given step of a pipeline.",
        "description": "Retrieve the log file for a build container or service container.\n\nThis endpoint supports (and encourages!) the use of [HTTP Range requests](https://tools.ietf.org/html/rfc7233) to deal with potentially very large log files.",
        "operationId": "getPipelineContainerLog",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get a summary of test reports for a given step of a pipeline.",
        "operationId": "getPipelineTestReports",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get test cases for a given step of a pipeline.",
        "operationId": "getPipelineTestReportTestCases",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases/{test_case_uuid}/test_case_reasons": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get test case reasons (output) for a given test case in a step of a pipeline.",
        "operationId": "getPipelineTestReportTestCaseReasons",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/stopPipeline": {
      "post": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Stop a pipeline",
        "description": "Signal the stop of a pipeline and all of its steps that not have completed yet.",
        "operationId": "stopPipeline",
        "security": [
          {
            "oauth2": [
              "pipeline:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get configuration",
        "description": "Retrieve the repository pipelines configuration.",
        "operationId": "getRepositoryPipelineConfig",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update configuration",
        "description": "Update the pipelines configuration for a repository.",
        "operationId": "updateRepositoryPipelineConfig",
        "security": [
          {
            "oauth2": [
              "repository:admin"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/build_number": {
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update the next build number",
        "description": "Update the next build number that should be assigned to a pipeline. The next build number that will be configured has to be strictly higher than the current latest build number for this repository.",
        "operationId": "updateRepositoryBuildNumber",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/schedules": {
      "post": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Create a schedule",
        "description": "Create a schedule for the given repository.",
        "operationId": "createRepositoryPipelineSchedule",
        "security": [
          {
            "oauth2": [
              "pipeline:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket",
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List schedules",
        "description": "Retrieve the configured schedules for the given repository.",
        "operationId": "getRepositoryPipelineSchedules",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get a schedule",
        "description": "Retrieve a schedule by its UUID.",
        "operationId": "getRepositoryPipelineSchedule",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update a schedule",
        "description": "Update a schedule.",
        "operationId": "updateRepositoryPipelineSchedule",
        "security": [
          {
            "oauth2": [
              "pipeline:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket",
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete a schedule",
        "description": "Delete a schedule.",
        "operationId": "deleteRepositoryPipelineSchedule",
        "security": [
          {
            "oauth2": [
              "pipeline:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/schedules/{schedule_uuid}/executions": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List executions of a schedule",
        "description": "Retrieve the executions of a given schedule.",
        "operationId": "getRepositoryPipelineScheduleExecutions",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/ssh/key_pair": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get SSH key pair",
        "description": "Retrieve the repository SSH key pair excluding the SSH private key. The private key is a write only field and will never be exposed in the logs or the REST API.",
        "operationId": "getRepositoryPipelineSshKeyPair",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update SSH key pair",
        "description": "Create or update the repository SSH key pair. The private key will be set as a default SSH identity in your build container.",
        "operationId": "updateRepositoryPipelineKeyPair",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete SSH key pair",
        "description": "Delete the repository SSH key pair.",
        "operationId": "deleteRepositoryPipelineKeyPair",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List known hosts",
        "description": "Find repository level known hosts.",
        "operationId": "getRepositoryPipelineKnownHosts",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Create a known host",
        "description": "Create a repository level known host.",
        "operationId": "createRepositoryPipelineKnownHost",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/ssh/known_hosts/{known_host_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get a known host",
        "description": "Retrieve a repository level known host.",
        "operationId": "getRepositoryPipelineKnownHost",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update a known host",
        "description": "Update a repository level known host.",
        "operationId": "updateRepositoryPipelineKnownHost",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete a known host",
        "description": "Delete a repository level known host.",
        "operationId": "deleteRepositoryPipelineKnownHost",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/variables": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "List variables for a repository",
        "description": "Find repository level variables.",
        "operationId": "getRepositoryPipelineVariables",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Create a variable for a repository",
        "description": "Create a repository level variable.",
        "operationId": "createRepositoryPipelineVariable",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pipelines_config/variables/{variable_uuid}": {
      "get": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Get a variable for a repository",
        "description": "Retrieve a repository level variable.",
        "operationId": "getRepositoryPipelineVariable",
        "security": [
          {
            "oauth2": [
              "pipeline"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "put": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Update a variable for a repository",
        "description": "Update a repository level variable.",
        "operationId": "updateRepositoryPipelineVariable",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "delete": {
        "tags": [
          "Pipelines"
        ],
        "summary": "Delete a variable for a repository",
        "description": "Delete a repository level variable.",
        "operationId": "deleteRepositoryPipelineVariable",
        "security": [
          {
            "oauth2": [
              "pipeline:variable"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:pipeline:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/properties/{app_key}/{property_name}": {
      "put": {
        "deprecated": true,
        "operationId": "updateRepositoryHostedPropertyValue",
        "summary": "Update a repository application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nUpdate an [application property](/cloud/bitbucket/application-properties/) value stored against a repository.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      },
      "delete": {
        "deprecated": true,
        "operationId": "deleteRepositoryHostedPropertyValue",
        "summary": "Delete a repository application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nDelete an [application property](/cloud/bitbucket/application-properties/) value stored against a repository.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "deprecated": true,
        "operationId": "getRepositoryHostedPropertyValue",
        "summary": "Get a repository application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nRetrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a repository.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:workspace:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns all pull requests on the specified repository.\n\nBy default only open pull requests are returned. This can be controlled\nusing the `state` query parameter. To retrieve pull requests that are\nin one of multiple states, repeat the `state` parameter for each\nindividual state.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.",
        "summary": "List pull requests",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests"
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Creates a new pull request where the destination repository is\nthis repository and the author is the authenticated user.\n\nThe minimum required fields to create a pull request are `title` and\n`source`, specified by a branch name.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/my-workspace/my-repository/pullrequests \\\n    -u my-username:my-password \\\n    --request POST \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n        \"title\": \[...]",
        "summary": "Create a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/activity": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a paginated list of the pull request's activity log.\n\nThis handler serves both a v20 and internal endpoint. The v20 endpoint\nreturns reviewer comments, updates, approvals and request changes. The internal\nendpoint includes those plus tasks and attachments.\n\nComments created on a file or a line of code have an inline property.\n\nComment example:\n```\n{\n    \"pagelen\": 20,\n    \"values\": [\n        {\n            \"comment\": {\n                \"links\"[...]",
        "summary": "List a pull request activity log",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_activity"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns the specified pull request.",
        "summary": "Get a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id"
      },
      "put": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Mutates the specified pull request.\n\nThis can be used to change the pull request's branches or description.\n\nOnly open pull requests can be mutated.",
        "summary": "Update a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_pullrequests_pull_request_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/activity": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a paginated list of the pull request's activity log.\n\nThis handler serves both a v20 and internal endpoint. The v20 endpoint\nreturns reviewer comments, updates, approvals and request changes. The internal\nendpoint includes those plus tasks and attachments.\n\nComments created on a file or a line of code have an inline property.\n\nComment example:\n```\n{\n    \"pagelen\": 20,\n    \"values\": [\n        {\n            \"comment\": {\n                \"links\"[...]",
        "summary": "List a pull request activity log",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_activity"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/approve": {
      "delete": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Redact the authenticated user's approval of the specified pull\nrequest.",
        "summary": "Unapprove a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_pullrequests_pull_request_id_approve"
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Approve the specified pull request as the authenticated user.",
        "summary": "Approve a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_approve"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a paginated list of the pull request's comments.\n\nThis includes both global, inline comments and replies.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more\ndetails.",
        "summary": "List comments on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments"
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Creates a new pull request comment.\n\nReturns the newly created pull request comment.",
        "summary": "Create a comment on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}": {
      "delete": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Deletes a specific pull request comment.",
        "summary": "Delete a comment on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments_comment_id"
      },
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a specific pull request comment.",
        "summary": "Get a comment on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments_comment_id"
      },
      "put": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Updates a specific pull request comment.",
        "summary": "Update a comment on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments_comment_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}/resolve": {
      "delete": {
        "tags": [
          "Pullrequests"
        ],
        "description": "",
        "summary": "Reopen a comment thread",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments_comment_id_resolve"
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "",
        "summary": "Resolve a comment thread",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_comments_comment_id_resolve"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/commits": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a paginated list of the pull request's commits.\n\nThese are the commits that are being merged into the destination\nbranch when the pull requests gets accepted.",
        "summary": "List commits on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_commits"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/conflicts": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Redirects to the [repository file conflicts](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-file-conflicts-spec-get)\nwith the revspec that corresponds to the pull request.",
        "summary": "Get file conflicts for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_conflicts"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/decline": {
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Declines the pull request.",
        "summary": "Decline a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_decline"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diff": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Redirects to the [repository diff](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-diff-spec-get)\nwith the revspec that corresponds to the pull request.",
        "summary": "List changes in a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_diff"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/diffstat": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Redirects to the [repository diffstat](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-diffstat-spec-get)\nwith the revspec that corresponds to the pull request.",
        "summary": "Get the diff stat for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_diffstat"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge": {
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Merges the pull request.",
        "summary": "Merge a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_merge"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge/task-status/{task_id}": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "When merging a pull request takes too long, the client receives a\ntask ID along with a 202 status code. The task ID can be used in a call\nto this endpoint to check the status of a merge task.\n\n```\ncurl -X GET https://api.bitbucket.org/2.0/repositories/atlassian/bitbucket/pullrequests/2286/merge/task-status/<task_id>\n```\n\nIf the merge task is not yet finished, a PENDING status will be returned.\n\n```\nHTTP/2 200\n{\n    \"task_status\": \"PENDING\",\n    \"links\"[...]",
        "summary": "Get the merge task status for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_merge_task_status_task_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/mergeability/checks": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns the mergeability checks Bitbucket performs for this pull request, and whether each one\ncurrently allows the pull request to be merged - simulating what the merge endpoint checks before\nactually merging.\n\nChecks cover pull request state, the current user's merge permissions, Git conflicts, configured\nstandard and custom merge checks, and merge queue status when available. Each check's `blocking`\nattribute indicates whether it currently prevents merging. A fai[...]",
        "summary": "List pull request mergeability checks",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_mergeability_checks"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/patch": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Redirects to the [repository patch](/cloud/bitbucket/rest/api-group-commits/#api-repositories-workspace-repo-slug-patch-spec-get)\nwith the revspec that corresponds to pull request.",
        "summary": "Get the patch for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_patch"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/request-changes": {
      "delete": {
        "tags": [
          "Pullrequests"
        ],
        "description": "",
        "summary": "Remove change request for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_pullrequests_pull_request_id_request_changes"
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "",
        "summary": "Request changes for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_request_changes"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/statuses": {
      "get": {
        "tags": [
          "Pullrequests",
          "Commit statuses"
        ],
        "description": "Returns all statuses (e.g. build results) for the given pull\nrequest.",
        "summary": "List commit statuses for a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_statuses"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a paginated list of the pull request's tasks.\n\nThis endpoint supports filtering and sorting of the results by the 'task' field.\nSee [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.",
        "summary": "List tasks on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks"
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Creates a new pull request task.\n\nReturns the newly created pull request task.\n\nTasks can optionally be created in relation to a comment specified by the comment's ID which\nwill cause the task to appear below the comment on a pull request when viewed in Bitbucket.",
        "summary": "Create a task on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/tasks/{task_id}": {
      "delete": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Deletes a specific pull request task.",
        "summary": "Delete a task on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks_task_id"
      },
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns a specific pull request task.",
        "summary": "Get a task on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks_task_id"
      },
      "put": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Updates a specific pull request task.",
        "summary": "Update a task on a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "put_repositories_workspace_repo_slug_pullrequests_pull_request_id_tasks_task_id"
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pullrequest_id}/properties/{app_key}/{property_name}": {
      "put": {
        "deprecated": true,
        "operationId": "updatePullRequestHostedPropertyValue",
        "summary": "Update a pull request application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nUpdate an [application property](/cloud/bitbucket/application-properties/) value stored against a pull \nrequest.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      },
      "delete": {
        "deprecated": true,
        "operationId": "deletePullRequestHostedPropertyValue",
        "summary": "Delete a pull request application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nDelete an [application property](/cloud/bitbucket/application-properties/) value stored against a pull\nrequest.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ]
      },
      "get": {
        "deprecated": true,
        "operationId": "getPullRequestHostedPropertyValue",
        "summary": "Get a pull request application property",
        "description": "This API will be deprecated on January 31, 2027 as part of [end of support for Connect app](https://community.developer.atlassian.com/t/bitbucket-cloud-announcing-connect-end-of-support-timeline-and-next-steps/98760).\n\nRetrieve an [application property](/cloud/bitbucket/application-properties/) value stored against a pull\nrequest.\n",
        "tags": [
          "properties"
        ],
        "security": [
          {
            "oauth2": []
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "admin:workspace:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs": {
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Returns the branches and tags in the repository.\n\nBy default, results will be in the order the underlying source control system returns them and identical to\nthe ordering one sees when running \"$ git show-ref\". Note that this follows simple\nlexical ordering of the ref names.\n\nThis can be undesirable as it does apply any natural sorting semantics, meaning for instance that refs are\nsorted [\"branch1\", \"branch10\", \"branch2\", \"v10\", \"v11\", \"v9\"] instead o[...]",
        "summary": "List branches and tags",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_refs"
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/branches": {
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Returns a list of all open branches within the specified repository.\nResults will be in the order the source control manager returns them.\n\nBranches support [filtering and sorting](/cloud/bitbucket/rest/intro/#filtering)\nthat can be used to search for specific branches. For instance, to find\nall branches that have \"stab\" in their name:\n\n```\ncurl -s https://api.bitbucket.org/2.0/repositories/atlassian/aui/refs/branches -G --data-urlencode 'q=name ~ \"stab\"'\n```[...]",
        "summary": "List open branches",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_refs_branches"
      },
      "post": {
        "tags": [
          "Refs"
        ],
        "description": "Creates a new branch in the specified repository.\n\nThe payload of the POST should consist of a JSON document that\ncontains the name of the tag and the target hash.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/branches \\\n-s -u seanfarley -X POST -H \"Content-Type: application/json\" \\\n-d '{\n    \"name\" : \"smf/create-feature\",\n    \"target\" : {\n        \"hash\" : \"default\",\n    }\n}'\n```\n\nThis call requires authentication. P[...]",
        "summary": "Create a branch",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket",
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_refs_branches"
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/branches/{name}": {
      "delete": {
        "tags": [
          "Refs"
        ],
        "description": "Delete a branch in the specified repository.\n\nThe main branch is not allowed to be deleted and will return a 400\nresponse.\n\nThe branch name should not include any prefixes (e.g.\nrefs/heads).",
        "summary": "Delete a branch",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_refs_branches_name"
      },
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Returns a branch object within the specified repository.\n\nThis call requires authentication. Private repositories require the\ncaller to authenticate with an account that has appropriate\nauthorization.\n\nFor Git, the branch name should not include any prefixes (e.g.\nrefs/heads).",
        "summary": "Get a branch",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_refs_branches_name"
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/tags": {
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Returns the tags in the repository.\n\nBy default, results will be in the order the underlying source control system returns them and identical to\nthe ordering one sees when running \"$ git tag --list\". Note that this follows simple\nlexical ordering of the ref names.\n\nThis can be undesirable as it does apply any natural sorting semantics, meaning for instance that tags are\nsorted [\"v10\", \"v11\", \"v9\"] instead of [\"v9\", \"v10\", \"v11\"].\n\nSorting can be cha[...]",
        "summary": "List tags",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_refs_tags"
      },
      "post": {
        "tags": [
          "Refs"
        ],
        "description": "Creates a new annotated tag in the specified repository.\n\nThe payload of the POST should consist of a JSON document that\ncontains the name of the tag and the target hash.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/jdoe/myrepo/refs/tags \\\n-s -u jdoe -X POST -H \"Content-Type: application/json\" \\\n-d '{\n    \"name\" : \"new-tag-name\",\n    \"target\" : {\n        \"hash\" : \"a1b2c3d4e5f6\",\n    }\n}'\n```\n\nThis endpoint does support using short has[...]",
        "summary": "Create a tag",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket",
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_refs_tags"
      }
    },
    "/repositories/{workspace}/{repo_slug}/refs/tags/{name}": {
      "delete": {
        "tags": [
          "Refs"
        ],
        "description": "Delete a tag in the specified repository.\n\nThe tag name should not include any prefixes (e.g. refs/tags).",
        "summary": "Delete a tag",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "delete_repositories_workspace_repo_slug_refs_tags_name"
      },
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Returns the specified tag.\n\n```\n$ curl -s https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/tags/3.8 -G | jq .\n{\n  \"name\": \"3.8\",\n  \"links\": {\n    \"commits\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/seanfarley/hg/commits/3.8\"\n    },\n    \"self\": {\n      \"href\": \"https://api.bitbucket.org/2.0/repositories/seanfarley/hg/refs/tags/3.8\"\n    },\n    \"html\": {\n      \"href\": \"https://bitbucket.org/seanfarley/hg/co[...]",
        "summary": "Get a tag",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_refs_tags_name"
      }
    },
    "/repositories/{workspace}/{repo_slug}/src": {
      "get": {
        "tags": [
          "Source",
          "Repositories"
        ],
        "description": "This endpoint redirects the client to the directory listing of the\nroot directory on the main branch.\n\nThis is equivalent to directly hitting\n[/2.0/repositories/{username}/{repo_slug}/src/{commit}/{path}](src/%7Bcommit%7D/%7Bpath%7D)\nwithout having to know the name or SHA1 of the repo's main branch.\n\nTo create new commits, [POST to this endpoint](#post)",
        "summary": "Get the root directory of the main branch",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_src"
      },
      "post": {
        "tags": [
          "Source",
          "Repositories"
        ],
        "description": "This endpoint is used to create new commits in the repository by\nuploading files.\n\nTo add a new file to a repository:\n\n```\n$ curl https://api.bitbucket.org/2.0/repositories/username/slug/src \\\n  -F /repo/path/to/image.png=@image.png\n```\n\nThis will create a new commit on top of the main branch, inheriting the\ncontents of the main branch, but adding (or overwriting) the\n`image.png` file to the repository in the `/repo/path/to` directory.\n\nTo create a commit t[...]",
        "summary": "Create a commit by uploading a file",
        "security": [
          {
            "oauth2": [
              "repository:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "post_repositories_workspace_repo_slug_src"
      }
    },
    "/repositories/{workspace}/{repo_slug}/src/{commit}/{path}": {
      "get": {
        "tags": [
          "Source",
          "Repositories"
        ],
        "description": "This endpoints is used to retrieve the contents of a single file,\nor the contents of a directory at a specified revision.\n\n#### Raw file contents\n\nWhen `path` points to a file, this endpoint returns the raw contents.\nThe response's Content-Type is derived from the filename\nextension (not from the contents). The file contents are not processed\nand no character encoding/recoding is performed and as a result no\ncharacter encoding is included as part of the Content-T[...]",
        "summary": "Get file or directory contents",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_src_commit_path"
      }
    },
    "/repositories/{workspace}/{repo_slug}/watchers": {
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Returns a paginated list of all the watchers on the specified\nrepository.",
        "summary": "List repositories watchers",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ],
        "operationId": "get_repositories_workspace_repo_slug_watchers"
      }
    },
    "/snippets": {
      "post": {
        "tags": [
          "Snippets"
        ],
        "description": "Creates a new snippet under the authenticated user's account.\n\nSnippets can contain multiple files. Both text and binary files are\nsupported.\n\nThe simplest way to create a new snippet from a local file:\n\n    $ curl -u username:password -X POST https://api.bitbucket.org/2.0/snippets               -F file=@image.png\n\nCreating snippets through curl has a few limitations and so let's look\nat a more complicated scenario.\n\nSnippets are created with a multipart POST.[...]",
        "summary": "Create a snippet",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket",
              "write:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "post_snippets"
      }
    },
    "/snippets/{workspace}": {
      "get": {
        "tags": [
          "Snippets"
        ],
        "description": "Returns a paginated list of snippets owned by `{workspace}`.\n\nTo limit the set of returned snippets, apply the\n`?role=[owner|contributor|member]` query parameter where the roles are\ndefined as follows:\n\n* `owner`: snippets owned by `{workspace}` that also belong to the current user\n    (only returns results when `{workspace}` is the current user's personal workspace)\n* `contributor`: snippets owned by `{workspace}` that the current user is watching,\n    plus any [...]",
        "summary": "List snippets in a workspace",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "get_snippets_workspace"
      },
      "post": {
        "tags": [
          "Snippets"
        ],
        "description": "Identical to [`/snippets`](/cloud/bitbucket/rest/api-group-snippets/#api-snippets-post), except that the new snippet will be\ncreated under the workspace specified in the path parameter\n`{workspace}`.",
        "summary": "Create a snippet for a workspace",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket",
              "write:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "post_snippets_workspace"
      }
    },
    "/snippets/{workspace}/{encoded_id}": {
      "delete": {
        "tags": [
          "Snippets"
        ],
        "description": "Deletes a snippet and returns an empty response.",
        "summary": "Delete a snippet",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "delete:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "delete_snippets_workspace_encoded_id"
      },
      "get": {
        "tags": [
          "Snippets"
        ],
        "description": "Retrieves a single snippet.\n\nSnippets support multiple content types:\n\n* application/json\n* multipart/related\n* multipart/form-data\n\n\napplication/json\n----------------\n\nThe default content type of the response is `application/json`.\nSince JSON is always `utf-8`, it cannot reliably contain file contents\nfor files that are not text. Therefore, JSON snippet documents only\ncontain the filename and links to the file contents.\n\nThis means that in order to retri[...]",
        "summary": "Get a snippet",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "get_snippets_workspace_encoded_id"
      },
      "put": {
        "tags": [
          "Snippets"
        ],
        "description": "Used to update a snippet. Use this to add and delete files and to\nchange a snippet's title.\n\nTo update a snippet, one can either PUT a full snapshot, or only the\nparts that need to be changed.\n\nThe contract for PUT on this API is that properties missing from the\nrequest remain untouched so that snippets can be efficiently\nmanipulated with differential payloads.\n\nTo delete a property (e.g. the title, or a file), include its name in\nthe request, but omit its valu[...]",
        "summary": "Update a snippet",
        "security": [
          {
            "oauth2": [
              "snippet:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket",
              "write:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "put_snippets_workspace_encoded_id"
      }
    },
    "/snippets/{workspace}/{encoded_id}/comments": {
      "get": {
        "tags": [
          "Snippets"
        ],
        "description": "Used to retrieve a paginated list of all comments for a specific\nsnippet.\n\nThis resource works identical to commit and pull request comments.\n\nThe default sorting is oldest to newest and can be overridden with\nthe `sort` query parameter.",
        "summary": "List comments on a snippet",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "get_snippets_workspace_encoded_id_comments"
      },
      "post": {
        "tags": [
          "Snippets"
        ],
        "description": "Creates a new comment.\n\nThe only required field in the body is `content.raw`.\n\nTo create a threaded reply to an existing comment, include `parent.id`.",
        "summary": "Create a comment on a snippet",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:snippet:bitbucket",
              "write:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "post_snippets_workspace_encoded_id_comments"
      }
    },
    "/snippets/{workspace}/{encoded_id}/comments/{comment_id}": {
      "delete": {
        "tags": [
          "Snippets"
        ],
        "description": "Deletes a snippet comment.\n\nComments can only be removed by the comment author, snippet creator, or workspace admin.",
        "summary": "Delete a comment on a snippet",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "write:snippet:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "api-token"
        ],
        "operationId": "delete_snippets_workspace_encoded_id_comments_comment_id"
      },
      "get": {
        "tags": [
          "Snippets"
        ],
        "description": "Returns the specific snippet comment.",
        "summary": "Get a comment on a snippet",
        "security": [
          {
            "oauth2": [
              "snippet"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
[...]
