{
  "openapi": "3.0.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "Create and manage meetings, conference records, participants, and meeting artifacts.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Meet",
    "version": "v2",
    "x-bionic-slug": "google-meet",
    "x-bionic-source-url": "https://meet.googleapis.com/$discovery/rest?version=v2",
    "x-bionic-logo-source-url": "https://raw.githubusercontent.com/gilbarbara/logos/main/logos/google-meet.svg",
    "x-logo": {
      "url": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMjU2cHgiIGhlaWdodD0iMjAxcHgiIHZpZXdCb3g9IjAgMCAyNTYgMjAxIiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHByZXNlcnZlQXNwZWN0UmF0aW89InhNaWRZTWlkIj4KICA8dGl0bGU+R29vZ2xlIEtlZXA8L3RpdGxlPgogIDxkZWZzPgogICAgICA8bGluZWFyR3JhZGllbnQgaWQ9ImEiIHgxPSIxMjguOCIgeDI9IjIyNy4yIiB5MT0iMTA0LjQ0IiB5Mj0iMTA0LjQ0IiBncmFkaWVudFVuaXRz[...]"
    }
  },
  "servers": [
    {
      "url": "https://meet.googleapis.com/"
    }
  ],
  "paths": {
    "/v2/conferenceRecords": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the conference records. By default, ordered by start time and in descending order. For more information, see [Work with conferences](https://developers.google.com/workspace/meet/api/guides/conferences).",
        "operationId": "meet.conferenceRecords.list"
      }
    },
    "/v2/spaces": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Creates a space. For more information, see [Manage meeting spaces](https://developers.google.com/workspace/meet/api/guides/manage-meeting-spaces).",
        "operationId": "meet.spaces.create"
      }
    },
    "/v2/{+name}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Deletes the member who was previously assigned roles in the space. For more information, see [Manage meeting space members](https://developers.google.com/workspace/meet/api/guides/meeting-space-members).",
        "operationId": "meet.spaces.members.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.settings"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Gets a member. For more information, see [Manage meeting space members](https://developers.google.com/workspace/meet/api/guides/meeting-space-members). This API supports the `fields` parameter in [SystemParameterContext](https://cloud.google.com/apis/docs/system-parameters). When the `fields` parameter is omitted, this API response will default to \"name,email,role,user\".",
        "operationId": "meet.spaces.members.get"
      },
      "patch": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.settings"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.settings"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Updates a member. For more information, see [Manage meeting space members](https://developers.google.com/workspace/meet/api/guides/meeting-space-members).",
        "operationId": "meet.spaces.members.patch"
      }
    },
    "/v2/{+name}:endActiveConference": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Ends an active conference (if there's one). For more information, see [Manage meeting spaces](https://developers.google.com/workspace/meet/api/guides/manage-meeting-spaces).",
        "operationId": "meet.spaces.endActiveConference"
      }
    },
    "/v2/{+parent}/entries": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the structured transcript entries per transcript. By default, ordered by start time and in ascending order. For more information, see [Work with artifacts](https://developers.google.com/workspace/meet/api/guides/artifacts). Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when 1) we have interleaved speakers within milliseconds, or 2) the Google Docs transcript fil[...]",
        "operationId": "meet.conferenceRecords.transcripts.entries.list"
      }
    },
    "/v2/{+parent}/members": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Lists members. For more information, see [Manage meeting space members](https://developers.google.com/workspace/meet/api/guides/meeting-space-members). This API supports the `fields` parameter in [SystemParameterContext](https://cloud.google.com/apis/docs/system-parameters). When the `fields` parameter is omitted this API response will default to \"name,email,role,user\".",
        "operationId": "meet.spaces.members.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Creates a member. For more information, see [Manage meeting space members](https://developers.google.com/workspace/meet/api/guides/meeting-space-members). This API supports the `fields` parameter in [SystemParameterContext](https://cloud.google.com/apis/docs/system-parameters). When the `fields` parameter is omitted, this API response will default to \"name,email,role,user\".",
        "operationId": "meet.spaces.members.create"
      }
    },
    "/v2/{+parent}/members:batchUpdate": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          }
        ],
        "tags": [
          "spaces"
        ],
        "description": "Updates members of one space within a batch. For more information, see [Manage meeting space members](https://developers.google.com/workspace/meet/api/guides/meeting-space-members).",
        "operationId": "meet.spaces.members.batchUpdate"
      }
    },
    "/v2/{+parent}/participantSessions": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the participant sessions of a participant in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted this API defaults to `'participantsessions/*, next_page_token'`. For more information, see [Work with participants](https://developers.google.com/workspace/meet/api/guides/participants).",
        "operationId": "meet.conferenceRecords.participants.participantSessions.list"
      }
    },
    "/v2/{+parent}/participants": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the participants in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted, this API defaults to `'participants/*, next_page_token'`. For more information, see [Work with participants](https://developers.google.com/workspace/meet/api/guides/participants).",
        "operationId": "meet.conferenceRecords.participants.list"
      }
    },
    "/v2/{+parent}/recordings": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the recording resources from the conference record. By default, ordered by start time and in ascending order. For more information, see [Work with artifacts](https://developers.google.com/workspace/meet/api/guides/artifacts).",
        "operationId": "meet.conferenceRecords.recordings.list"
      }
    },
    "/v2/{+parent}/smartNotes": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the set of smart notes from the conference record. By default, ordered by start time and in ascending order. For more information, see [Work with artifacts](https://developers.google.com/workspace/meet/api/guides/artifacts).",
        "operationId": "meet.conferenceRecords.smartNotes.list"
      }
    },
    "/v2/{+parent}/transcripts": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.created"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/meetings.space.readonly"
            ]
          }
        ],
        "tags": [
          "conferenceRecords"
        ],
        "description": "Lists the set of transcripts from the conference record. By default, ordered by start time and in ascending order. For more information, see [Work with artifacts](https://developers.google.com/workspace/meet/api/guides/artifacts).",
        "operationId": "meet.conferenceRecords.transcripts.list"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/meetings.space.created": "Create, edit, and see information about your Google Meet conferences created by the app.",
              "https://www.googleapis.com/auth/meetings.space.readonly": "Read information about any of your Google Meet conferences",
              "https://www.googleapis.com/auth/meetings.space.settings": "Edit, and see settings for all of your Google Meet calls."
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 accessCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/meetings.space.created": "Create, edit, and see information about your Google Meet conferences created by the app.",
              "https://www.googleapis.com/auth/meetings.space.readonly": "Read information about any of your Google Meet conferences",
              "https://www.googleapis.com/auth/meetings.space.settings": "Edit, and see settings for all of your Google Meet calls."
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "name": "conferenceRecords"
    },
    {
      "name": "spaces"
    }
  ]
}
