{
  "openapi": "3.0.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "Create and manage data transfer requests between Workspace users for supported data types.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Workspace Admin: Data Transfer",
    "version": "datatransfer_v1",
    "x-bionic-slug": "google-workspace-admin-data-transfer",
    "x-bionic-source-url": "https://admin.googleapis.com/$discovery/rest?version=datatransfer_v1",
    "x-bionic-logo-source-url": "https://knowledge.workspace.google.com/static/images/icons/product/admin-console.svg",
    "x-logo": {
      "url": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDE5MiAxOTIiIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDE5MiAxOTIiIHdpZHRoPSIyNHB4Ij48cmVjdCBmaWxsPSJub25lIiBoZWlnaHQ9IjE5MiIgd2lkdGg9IjE5MiIvPjxnPjxnPjxwYXRoIGQ9Ik0yNC41MywxMzBsMjAuNjksMzUuODRjMy4yNyw1LjY3LDkuMzIsOS4xNiwxNS44Niw5LjE2aDQ0LjA2bC03LjkzLTI0LjA3TDc4LjE1LDEzMGwtMjYuODEtNC42NiBMMjQuNTMsMTMweiIgZmlsbD0iIzE5NjdEMiIvPjxwYXRoIGQ9Ik0xODIuMDYsODYuODRsLTIwLjA5LTM0LjhsLTE3[...]"
    }
  },
  "servers": [
    {
      "url": "https://admin.googleapis.com/"
    }
  ],
  "paths": {
    "/admin/datatransfer/v1/applications": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ]
          }
        ],
        "tags": [
          "applications"
        ],
        "description": "Lists the applications available for data transfer for a customer.",
        "operationId": "datatransfer.applications.list"
      }
    },
    "/admin/datatransfer/v1/applications/{applicationId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ]
          }
        ],
        "tags": [
          "applications"
        ],
        "description": "Retrieves information about an application for the given application ID.",
        "operationId": "datatransfer.applications.get"
      }
    },
    "/admin/datatransfer/v1/transfers": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ]
          }
        ],
        "tags": [
          "transfers"
        ],
        "description": "Lists the transfers for a customer by source user, destination user, or status.",
        "operationId": "datatransfer.transfers.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ]
          }
        ],
        "tags": [
          "transfers"
        ],
        "description": "Inserts a data transfer request. See the [Transfer parameters](https://developers.google.com/workspace/admin/data-transfer/v1/parameters) reference for specific application requirements.",
        "operationId": "datatransfer.transfers.insert"
      }
    },
    "/admin/datatransfer/v1/transfers/{dataTransferId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.datatransfer.readonly"
            ]
          }
        ],
        "tags": [
          "transfers"
        ],
        "description": "Retrieves a data transfer request by its resource ID.",
        "operationId": "datatransfer.transfers.get"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/admin.datatransfer": "View and manage data transfers between users in your organization",
              "https://www.googleapis.com/auth/admin.datatransfer.readonly": "View data transfers between users in your organization"
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 accessCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/admin.datatransfer": "View and manage data transfers between users in your organization",
              "https://www.googleapis.com/auth/admin.datatransfer.readonly": "View data transfers between users in your organization"
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "name": "applications"
    },
    {
      "name": "transfers"
    }
  ]
}
