{
  "openapi": "3.0.1",
  "x-settings": {
    "publish": true
  },
  "info": {
    "title": "Miro",
    "version": "v2.0",
    "description": "Create and manage Miro boards, items, teams, and collaboration resources through the Miro REST API.",
    "x-bionic-slug": "miro",
    "x-bionic-source-url": "https://github.com/miroapp/api-clients/blob/main/packages/generator/spec.json",
    "x-logo": {
      "url": "data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+TWlybzwvdGl0bGU+PHBhdGggZmlsbD0iIzA1MDAzOCIgZD0iTTE3LjM5MiAwSDEzLjlMMTcgNC44MDggMTAuNDQ0IDBINi45NDlsMy4xMDIgNi4zTDMuNDk0IDBIMGwzLjA1IDguMTMxTDAgMjRoMy40OTRMMTAuMDUgNi45ODUgNi45NDkgMjRoMy40OTRMMTcgNS40OTQgMTMuODk5IDI0aDMuNDkzTDI0IDMuNjcyIDE3LjM5MiAweiIvPjwvc3ZnPg=="
    }
  },
  "servers": [
    {
      "url": "https://api.miro.com/"
    }
  ],
  "paths": {
    "/v1/oauth/revoke": {
      "post": {
        "tags": [
          "tokens"
        ],
        "summary": "Revoke token (v1)",
        "description": "<p><b>Please use the new revoke endpoint <code>/v2/oauth/revoke</code>. This endpoint is considered vulnerable and deprecated due to access token passed publicly in the URL.</b></p> Revoke the current access token. Revoking an access token means that the access token will no longer work. When an access token is revoked, the refresh token is also revoked and no longer valid. This does not uninstall the application for the user.",
        "operationId": "revoke-token",
        "deprecated": true
      }
    },
    "/v1/oauth-token": {
      "get": {
        "tags": [
          "tokens"
        ],
        "summary": "Get access token information",
        "description": "Get information about an access token, such as the token type, scopes, team, user, token creation date and time, and the user who created the token.",
        "operationId": "token-info"
      }
    },
    "/v2/orgs/{org_id}/ai-interaction-logs": {
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "description": "Retrieves AI interaction logs for your organization. AI interaction logs capture user interactions with AI features in Miro. You can retrieve results for a specific time period. You can also filter results based on object IDs and the emails of users who interacted with AI features. Additionally, results can be paginated for easier viewing and processing.\n<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>aiinteractionlogs:read[...]",
        "operationId": "enterprise-get-ai-interaction-logs",
        "summary": "Get AI interaction logs (Beta)",
        "tags": [
          "AI Interaction Logs"
        ]
      }
    },
    "/v2/audit/logs": {
      "get": {
        "description": "Retrieves a page of audit events from the last 90 days. If you want to retrieve data that is older than 90 days, you can use the <a target=_blank href=\"https://help.miro.com/hc/en-us/articles/360017571434-Audit-logs#h_01J7EY4E0F67EFTRQ7BT688HW0\">CSV export feature</a>.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>auditlogs:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-ti[...]",
        "operationId": "enterprise-get-audit-logs",
        "summary": "Get audit logs",
        "tags": [
          "Audit Logs"
        ]
      }
    },
    "/v2/orgs/{org_id}/data-classification-settings": {
      "get": {
        "description": "Retrieves board classification settings for an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this [...]",
        "operationId": "enterprise-dataclassification-organization-settings-get",
        "summary": "Get organization settings",
        "tags": [
          "Board classification: Organization level"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/data-classification": {
      "patch": {
        "description": "Updates board classification for not-classified only or all boards in an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can on[...]",
        "operationId": "enterprise-dataclassification-team-boards-bulk",
        "summary": "Bulk update boards classification",
        "tags": [
          "Board classification: Team level"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/data-classification-settings": {
      "get": {
        "description": "Retrieves board classification settings for an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this en[...]",
        "operationId": "enterprise-dataclassification-team-settings-get",
        "summary": "Get team settings",
        "tags": [
          "Board classification: Team level"
        ]
      },
      "patch": {
        "description": "Updates board classification settings for an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this end[...]",
        "operationId": "enterprise-dataclassification-team-settings-set",
        "x-settings": {
          "skip-tests": true
        },
        "summary": "Update team settings",
        "tags": [
          "Board classification: Team level"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/boards/{board_id}/data-classification": {
      "get": {
        "description": "Retrieves board classification for a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of [...]",
        "operationId": "enterprise-dataclassification-board-get",
        "x-settings": {
          "skip-tests": true
        },
        "summary": "Get board classification",
        "tags": [
          "Board classification: Board level"
        ]
      },
      "post": {
        "description": "Updates board classification for an existing board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the[...]",
        "operationId": "enterprise-dataclassification-board-set",
        "x-settings": {
          "skip-tests": true
        },
        "summary": "Update board classification",
        "tags": [
          "Board classification: Board level"
        ]
      }
    },
    "/v2/boards/{board_id}/docs": {
      "post": {
        "description": "Adds a doc format item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-doc-format-item",
        "summary": "Create doc format item",
        "tags": [
          "doc formats"
        ]
      }
    },
    "/v2/boards/{board_id}/docs/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific doc format item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-doc-format-item",
        "summary": "Get doc format item",
        "tags": [
          "doc formats"
        ]
      },
      "delete": {
        "description": "Deletes a doc format item from the board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-doc-format-item",
        "summary": "Delete doc format item",
        "tags": [
          "doc formats"
        ]
      }
    },
    "/v2/orgs/{org_id}/cases": {
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Get all cases",
        "operationId": "get-all-cases",
        "description": "Retrieves the list of eDiscovery cases in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organization:cases:management</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise Guard only</h3> <p>This API is available only for Enterprise plan users with the <a target=_blank href=\"https://help.miro.com/hc/en-us/articles/15699815402514-[...]",
        "tags": [
          "Legal holds"
        ]
      },
      "post": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Create case",
        "operationId": "create-case",
        "description": "Creating a case for legal hold is the first critical step in the eDiscovery process when litigation or an investigation is anticipated. One of the purposes of creating a case is that it acts as a container that allows admins to group multiple legal holds under one case. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/22120022370962-Create-a-case\" target=_blank>Help Center page on creating a case</a>. <br><br>This API creates a new case in [...]",
        "tags": [
          "Legal holds"
        ]
      }
    },
    "/v2/orgs/{org_id}/cases/{case_id}": {
      "delete": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Close case",
        "operationId": "delete-case",
        "description": "Closing a case is the final stage in the eDiscovery process, marking the conclusion of a legal matter or investigation. You must ensure that all associated legal holds within the case are closed before closing the case. Closing a case will permanently delete it. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/22138936297746-Close-a-case\" target=_blank>Help Center page on closing a case</a>. <br><br>This API closes a case in an organization[...]",
        "tags": [
          "Legal holds"
        ]
      },
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Get case",
        "operationId": "get-case",
        "description": "Retrieves information about a case in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organization:cases:management</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a> <br/><h3>Enterprise Guard only</h3> <p>This API is available only for Enterprise plan users with the <a target=_blank href=\"https://help.miro.com/hc/en-us/articles/15699815402514-Ente[...]",
        "tags": [
          "Legal holds"
        ]
      },
      "put": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Edit case",
        "operationId": "edit-case",
        "description": "Editing a case allows eDiscovery Admins to keep case details accurate and aligned with the evolving scope of a legal matter. As investigations progress, it may be necessary to update the case name or description to reflect changes in focus, terminology, or internal documentation standards. Since a case serves as the central container for one or more legal holds, keeping its information up to date helps ensure clarity, consistency, and easier navigation for all stakeholder[...]",
        "tags": [
          "Legal holds"
        ]
      }
    },
    "/v2/orgs/{org_id}/cases/{case_id}/legal-holds": {
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Get all legal holds within a case",
        "operationId": "get-all-legal-holds",
        "description": "Retrieves the list of all legal holds within a case for an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organization:cases:management</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise Guard only</h3> <p>This API is available only for Enterprise plan users with the <a target=_blank href=\"https://help.miro.com/hc/en-us/articles/1[...]",
        "tags": [
          "Legal holds"
        ]
      },
      "post": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Create legal hold",
        "operationId": "create-legal-hold",
        "description": "After creating a case it is possible to add one or multiple legal holds to the case. Creating a legal hold involves identifying the relevant users associated with a case and applying the hold to prevent permanent deletion of content that those users own, co-own, create, edit or access. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/22120471564946-Add-a-legal-hold-to-a-case\" target=_blank>Help Center page on adding a legal hold to a case</[...]",
        "tags": [
          "Legal holds"
        ]
      }
    },
    "/v2/orgs/{org_id}/cases/{case_id}/export-jobs": {
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Get board export jobs of a case",
        "operationId": "get-legal-hold-export-jobs",
        "description": "Retrieves board export jobs for a case.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organization:cases:management</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise Guard only</h3> <p>This API is available only for Enterprise plan users with the <a target=_blank href=\"https://help.miro.com/hc/en-us/articles/15699815402514-Enterprise-Guard-ov[...]",
        "tags": [
          "Legal holds"
        ]
      }
    },
    "/v2/orgs/{org_id}/cases/{case_id}/legal-holds/{legal_hold_id}": {
      "delete": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Close legal hold",
        "operationId": "delete-legal-hold",
        "description": "Closing a legal hold is one of the final steps in the eDiscovery process once the litigation or investigation has concluded. This process involves releasing the Miro boards and custodians that were under legal hold, allowing the preserved boards to return to normal operations. Closing a legal hold will permanently delete it. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/21922521629330-Close-a-legal-hold\" target=_blank>Help Center page on[...]",
        "tags": [
          "Legal holds"
        ]
      },
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Get legal hold information",
        "operationId": "get-legal-hold",
        "description": "Retrieves information about a legal hold within a case for an organization. <br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organization:cases:management</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a> <br/><h3>Enterprise Guard only</h3> <p>This API is available only for Enterprise plan users with the <a target=_blank href=\"https://help.miro.com/hc/en-us/articl[...]",
        "tags": [
          "Legal holds"
        ]
      },
      "put": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Edit legal hold",
        "operationId": "edit-legal-hold",
        "description": "Editing a legal hold allows eDiscovery Admins to adjust and refine ongoing legal preservation efforts as case requirements evolve. Whether new custodians are identified, additional Miro boards become relevant, or existing boards or users are no longer in scope, editing a legal hold ensures that the correct data remains preserved and defensible throughout the legal process. Admins can update the legal hold’s name or description and add or remove users and boards as needed.[...]",
        "tags": [
          "Legal holds"
        ]
      }
    },
    "/v2/orgs/{org_id}/cases/{case_id}/legal-holds/{legal_hold_id}/content-items": {
      "get": {
        "x-settings": {
          "publish": true,
          "skip-tests": true
        },
        "summary": "Get content items under legal hold",
        "operationId": "get-legal-hold-content-items",
        "description": "Once a legal hold is in place you can review or explore the preserved Miro boards to ensure that all relevant data is intact and ready for legal proceedings or investigations. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/22120628583570-Review-boards-under-legal-hold\" target=_blank>Help Center page on reviewing boards under legal hold</a>. <br><br>This API lists all content items under a specific legal hold in a case for an organization.[...]",
        "tags": [
          "Legal holds"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Creates an export job for one or more boards.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role[...]",
        "operationId": "enterprise-create-board-export",
        "summary": "Create board export job",
        "tags": [
          "Board Export"
        ]
      },
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves the list of board export jobs based on the filters provided in the request.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can onl[...]",
        "operationId": "enterprise-board-export-jobs",
        "summary": "Get board export jobs list",
        "tags": [
          "Board Export"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves the status of the board export job.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role[...]",
        "operationId": "enterprise-board-export-job-status",
        "summary": "Get board export job status",
        "tags": [
          "Board Export"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/results": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves the result of the board export job. The response provides more information about the board export job, such as the S3 link to the files created.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/a[...]",
        "operationId": "enterprise-board-export-job-results",
        "summary": "Get results for board export job",
        "tags": [
          "Board Export"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/status": {
      "put": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Updates the status of the board export job.<br/>Currently, only the cancellation of an ongoing export job is supported.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Ente[...]",
        "operationId": "enterprise-update-board-export-job",
        "summary": "Update board export job status",
        "tags": [
          "Board Export"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/tasks": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves the list of tasks for the board export job.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have [...]",
        "operationId": "enterprise-board-export-job-tasks",
        "summary": "Get board export job tasks list",
        "tags": [
          "Board Export"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/tasks/{task_id}/export-link": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Creates a link to download the results of a board export task.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if [...]",
        "operationId": "enterprise-create-board-export-task-export-link",
        "summary": "Create task export link",
        "tags": [
          "Board Export"
        ]
      }
    },
    "/v2/orgs/{org_id}/content-logs/items": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves content changes for board items within your organization. Content changes are actions that users can perform on board items, such as updating a sticky note's text. You can retrieve results for a specific time period. You can also filter results based on the board IDs and the emails of users who created, modified, or deleted a board item. Additionally, results can be paginated for easier viewing and processing.\n<br/><h3>Required scope</h3> <a target=_blank href=[...]",
        "operationId": "enterprise-board-content-item-logs-fetch",
        "summary": "Retrieve content change logs of board items",
        "tags": [
          "Board Content Logs"
        ]
      }
    },
    "/v2/sessions/reset_all": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Reset all sessions of a user.  Admins can now take immediate action to restrict user access to company data in case of security concerns. Calling this API ends all active Miro sessions across devices for a particular user, requiring the user to sign in again. This is useful in situations where a user leaves the company, their credentials are compromised, or there's suspicious activity on their account.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.m[...]",
        "operationId": "enterprise-post-user-sessions-reset",
        "summary": "Reset all sessions of a user",
        "tags": [
          "Reset all sessions of a user"
        ]
      }
    },
    "/Users": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Retrieves the list of users in your organization. <br><b> <br>Note</b>: The API returns users that are members in the organization, it does not return users that are added in the organization as guests.",
        "operationId": "listUsers",
        "summary": "List users"
      },
      "post": {
        "tags": [
          "User"
        ],
        "description": "Creates a new user in the organization. <br><br> <br>Note</b>: All newly provisioned users are added to the default team.",
        "operationId": "createUser",
        "summary": "Create user"
      }
    },
    "/Users/{id}": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Retrieves a single user resource. <br><b> <br>Note</b>: Returns only users that are members in the organization. It does not return users that are added in the organization as guests.",
        "operationId": "getUser",
        "summary": "Get user"
      },
      "put": {
        "tags": [
          "User"
        ],
        "description": "Updates an existing user resource. This is the easiest way to replace user information. <br><br> If the user is deactivated, <br> userName, userType, and roles.value cannot be updated. <br> emails.value, emails.display, emails.primary get ignored and do not return any error. <br><br> Note: If the user is not a member in the organization, they cannot be updated. Additionally, users with guest role in the organization cannot be updated. ",
        "operationId": "replaceUser",
        "summary": "Replace user"
      },
      "patch": {
        "tags": [
          "User"
        ],
        "description": "Updates an existing user resource, overwriting values for specified attributes. Attributes that are not provided will remain unchanged. PATCH operation only updates the fields provided. <br><br> Note: If  the user is not a member in the organization, they cannot be updated. Additionally, users with guest role in the organization cannot be updated. ",
        "operationId": "patchUser",
        "summary": "Patch user"
      },
      "delete": {
        "tags": [
          "User"
        ],
        "operationId": "deleteUser",
        "summary": "Delete user",
        "description": "Deletes a single user from the organization.<br><br> Note: A user who is the last admin in the team or the last admin in the organization cannot be deleted. User must be a member in the organization to be deleted. Users that have guest role in the organization cannot be deleted. <br><br> After a user is deleted, the ownership of all the boards that belong to the deleted user is transferred to the oldest team member who currently has an admin role."
      }
    },
    "/Groups": {
      "get": {
        "tags": [
          "Group"
        ],
        "description": "Retrieves the list of groups (teams) in the organization.<br><br> Note: Along with groups (teams), the users that are part of those groups (teams) are also retrieved. Only users that have member role in the organization are fetched.",
        "operationId": "listGroups",
        "summary": "List groups"
      }
    },
    "/Groups/{id}": {
      "get": {
        "tags": [
          "Group"
        ],
        "description": "Retrieves a single Group resource.<br><b> Note</b>: Along with groups (teams), the users that are part of those groups (teams) are also retrieved. Only users that have member role in the organization are fetched.",
        "operationId": "getGroup",
        "summary": "Get group"
      },
      "patch": {
        "tags": [
          "Group"
        ],
        "description": "Updates an existing group resource, i.e. a team, overwriting values for specified attributes. Patch operation for group can be used to add, remove, or replace team members and to update the display name of the group (team). <br><br> To add a user to the group (team), use add operation. <br> To remove a user from a group (team), use remove operation. <br> To update a user resource, use the replace operation. <br> The last team admin cannot be removed from the team. <br><br[...]",
        "operationId": "patchGroup",
        "summary": "Patch group"
      }
    },
    "/ServiceProviderConfig": {
      "get": {
        "tags": [
          "Discovery"
        ],
        "description": "Retrieve supported operations and SCIM API basic configuration.",
        "operationId": "listServiceProviderConfigs",
        "summary": "Get Service Provider Config"
      }
    },
    "/ResourceTypes": {
      "get": {
        "tags": [
          "Discovery"
        ],
        "description": "Retrieve information about which SCIM resources are supported. <br><br> Currently, Miro supports Users and Groups as Resource Types.",
        "operationId": "listResourceTypes",
        "summary": "List resource types"
      }
    },
    "/ResourceTypes/{resource}": {
      "get": {
        "tags": [
          "Discovery"
        ],
        "description": "Retrieve metadata for the available resource types (User and Group) that are supported.",
        "operationId": "getResourceType",
        "summary": "Get resource type"
      }
    },
    "/Schemas": {
      "get": {
        "tags": [
          "Discovery"
        ],
        "description": "Retrieve metadata about Users, Groups, and extension attributes that are currently supported.",
        "operationId": "listSchemas",
        "summary": "List schemas"
      }
    },
    "/Schemas/{uri}": {
      "get": {
        "tags": [
          "Discovery"
        ],
        "description": "Retrieve information about how users, groups, and enterprise-user attributes URIs that are formatted.",
        "operationId": "getSchema",
        "summary": "Get schema"
      }
    },
    "/v2/orgs/{org_id}": {
      "get": {
        "description": "Retrieves organization information.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a[...]",
        "operationId": "enterprise-get-organization",
        "summary": "Get organization info",
        "tags": [
          "Organizations"
        ]
      }
    },
    "/v2/orgs/{org_id}/members": {
      "get": {
        "description": "Retrieves organization members based on the organization ID and the cursor, or based on the user emails provided in the request.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterpri[...]",
        "operationId": "enterprise-get-organization-members",
        "summary": "Get organization members",
        "tags": [
          "Organization Members"
        ]
      }
    },
    "/v2/orgs/{org_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves organization member information for an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use thi[...]",
        "operationId": "enterprise-get-organization-member",
        "summary": "Get organization member",
        "tags": [
          "Organization Members"
        ]
      }
    },
    "/v2/boards": {
      "post": {
        "description": "Creates a board with the specified name and sharing policies.<br/><h4>Note</h4> You can only create up to 3 team boards with the free plan.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "create-board",
        "summary": "Create board",
        "tags": [
          "Boards"
        ]
      },
      "get": {
        "description": "Retrieves a list of boards accessible to the user associated with the provided access token. This endpoint supports filtering and sorting through URL query parameters.\nCustomize the response by specifying `team_id`, `project_id`, or other query parameters. Filtering by `team_id` or `project_id` (or both) returns results instantly. For other filters, allow a few seconds for indexing of newly created boards.\n\nIf you're an Enterprise customer with Company Admin permission[...]",
        "operationId": "get-boards",
        "summary": "Get boards",
        "tags": [
          "Boards"
        ]
      },
      "put": {
        "description": "Creates a copy of an existing board. You can also update the name, description, sharing policy, and permissions policy for the new board in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a><br/>",
        "operationId": "copy-board",
        "summary": "Copy board",
        "tags": [
          "Boards"
        ]
      }
    },
    "/v2/boards/{board_id}": {
      "get": {
        "description": "Retrieves information about a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-specific-board",
        "summary": "Get specific board",
        "tags": [
          "Boards"
        ]
      },
      "patch": {
        "description": "Updates a specific board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-board",
        "summary": "Update board",
        "tags": [
          "Boards"
        ]
      },
      "delete": {
        "description": "Deletes a board. Deleted boards go to Trash (on paid plans) and can be restored via UI within 90 days after deletion.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-board",
        "summary": "Delete board",
        "tags": [
          "Boards"
        ]
      }
    },
    "/v2/boards/{board_id}/app_cards": {
      "post": {
        "description": "Adds an app card item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-app-card-item",
        "summary": "Create app card item",
        "tags": [
          "App card items"
        ]
      }
    },
    "/v2/boards/{board_id}/app_cards/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific app card item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-app-card-item",
        "summary": "Get app card item",
        "tags": [
          "App card items"
        ]
      },
      "patch": {
        "description": "Updates an app card item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-app-card-item",
        "summary": "Update app card item",
        "tags": [
          "App card items"
        ]
      },
      "delete": {
        "description": "Deletes an app card item from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-app-card-item",
        "summary": "Delete app card item",
        "tags": [
          "App card items"
        ]
      }
    },
    "/v2/boards/{board_id}/cards": {
      "post": {
        "description": "Adds a card item to a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "x-settings": {
          "skip-tests": true
        },
        "operationId": "create-card-item",
        "summary": "Create card item",
        "tags": [
          "Card items"
        ]
      }
    },
    "/v2/boards/{board_id}/cards/{item_id}": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves information for a specific card item on a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-card-item",
        "summary": "Get card item",
        "tags": [
          "Card items"
        ]
      },
      "patch": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Updates a card item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-card-item",
        "summary": "Update card item",
        "tags": [
          "Card items"
        ]
      },
      "delete": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Deletes a card item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-card-item",
        "summary": "Delete card item",
        "tags": [
          "Card items"
        ]
      }
    },
    "/v2/boards/{board_id}/connectors": {
      "post": {
        "description": "Adds a connector to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-connector",
        "summary": "Create connector",
        "tags": [
          "Connectors"
        ]
      },
      "get": {
        "description": "Retrieves a list of connectors for a specific board.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the response of the previous request. For [...]",
        "operationId": "get-connectors",
        "summary": "Get connectors",
        "tags": [
          "Connectors"
        ]
      }
    },
    "/v2/boards/{board_id}/connectors/{connector_id}": {
      "get": {
        "description": "Retrieves information for a specific connector on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-connector",
        "summary": "Get specific connector",
        "tags": [
          "Connectors"
        ]
      },
      "patch": {
        "description": "Updates a connector on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-connector",
        "summary": "Update connector",
        "tags": [
          "Connectors"
        ]
      },
      "delete": {
        "description": "Deletes the specified connector from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-connector",
        "summary": "Delete connector",
        "tags": [
          "Connectors"
        ]
      }
    },
    "/v2/boards/{board_id}/documents": {
      "post": {
        "description": "Adds a document item to a board by specifying the URL where the document is hosted.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-document-item-using-url",
        "summary": "Create document item using URL",
        "tags": [
          "Document items"
        ]
      }
    },
    "/v2/boards/{board_id}/documents/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific document item on a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-document-item",
        "summary": "Get document item",
        "tags": [
          "Document items"
        ]
      },
      "patch": {
        "description": "Updates a document item on a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-document-item-using-url",
        "summary": "Update document item using URL",
        "tags": [
          "Document items"
        ]
      },
      "delete": {
        "description": "Deletes a document item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-document-item",
        "summary": "Delete document item",
        "tags": [
          "Document items"
        ]
      }
    },
    "/v2/boards/{board_id}/embeds": {
      "post": {
        "description": "Adds an embed item containing external content to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-embed-item",
        "summary": "Create embed item",
        "tags": [
          "Embed items"
        ]
      }
    },
    "/v2/boards/{board_id}/embeds/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific embed item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-embed-item",
        "summary": "Get embed item",
        "tags": [
          "Embed items"
        ]
      },
      "patch": {
        "description": "Updates an embed item on a board based on the data properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-embed-item",
        "summary": "Update embed item",
        "tags": [
          "Embed items"
        ]
      },
      "delete": {
        "description": "Deletes an embed item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-embed-item",
        "summary": "Delete embed item",
        "tags": [
          "Embed items"
        ]
      }
    },
    "/v2/boards/{board_id}/images": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Adds an image item to a board by specifying an image URL.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-image-item-using-url",
        "summary": "Create image item using URL",
        "tags": [
          "Image items"
        ]
      }
    },
    "/v2/boards/{board_id}/images/{item_id}": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves information for a specific image item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-image-item",
        "summary": "Get image item",
        "tags": [
          "Image items"
        ]
      },
      "patch": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Updates an image item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-image-item-using-url",
        "summary": "Update image item using URL",
        "tags": [
          "Image items"
        ]
      },
      "delete": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Deletes an image item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-image-item",
        "summary": "Delete image item",
        "tags": [
          "Image items"
        ]
      }
    },
    "/v2/boards/{board_id}/items": {
      "get": {
        "description": "Retrieves a list of items for a specific board. You can retrieve all items on the board, a list of child items inside a parent item, or a list of specific types of items by specifying URL query parameter values.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the coll[...]",
        "operationId": "get-items",
        "summary": "Get items on board",
        "tags": [
          "Items"
        ]
      }
    },
    "/v2/boards/{board_id}/items/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-specific-item",
        "summary": "Get specific item on board",
        "tags": [
          "Items"
        ]
      },
      "patch": {
        "description": "Updates the position or the parent of an item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-item-position-or-parent",
        "summary": "Update item position or parent",
        "tags": [
          "Items"
        ]
      },
      "delete": {
        "description": "Deletes an item from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-item",
        "summary": "Delete item",
        "tags": [
          "Items"
        ]
      }
    },
    "/v2/boards/{board_id}/members": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Shares the board and Invites new members to collaborate on a board by sending an invitation email. Depending on the board's Sharing policy, there might be various scenarios where membership in the team is required in order to share the board with a user.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><b[...]",
        "operationId": "share-board",
        "summary": "Share board",
        "tags": [
          "Board members"
        ]
      },
      "get": {
        "description": "Retrieves a pageable list of members for a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-board-members",
        "summary": "Get all board members",
        "tags": [
          "Board members"
        ]
      }
    },
    "/v2/boards/{board_id}/members/{board_member_id}": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves information for a board member.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-specific-board-member",
        "summary": "Get specific board member",
        "tags": [
          "Board members"
        ]
      },
      "patch": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Updates the role of a board member.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-board-member",
        "summary": "Update board member",
        "tags": [
          "Board members"
        ]
      },
      "delete": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Removes a board member from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "remove-board-member",
        "summary": "Remove board member",
        "tags": [
          "Board members"
        ]
      }
    },
    "/v2/boards/{board_id}/shapes": {
      "post": {
        "description": "Adds a shape item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-shape-item",
        "summary": "Create shape item",
        "tags": [
          "Shape items"
        ]
      }
    },
    "/v2/boards/{board_id}/shapes/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific shape item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-shape-item",
        "summary": "Get shape item",
        "tags": [
          "Shape items"
        ]
      },
      "patch": {
        "description": "Updates a shape item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-shape-item",
        "summary": "Update shape item",
        "tags": [
          "Shape items"
        ]
      },
      "delete": {
        "description": "Deletes a shape item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-shape-item",
        "summary": "Delete shape item",
        "tags": [
          "Shape items"
        ]
      }
    },
    "/v2/boards/{board_id}/sticky_notes": {
      "post": {
        "description": "Adds a sticky note item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-sticky-note-item",
        "summary": "Create sticky note item",
        "tags": [
          "Sticky note items"
        ]
      }
    },
    "/v2/boards/{board_id}/sticky_notes/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific sticky note item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-sticky-note-item",
        "summary": "Get sticky note item",
        "tags": [
          "Sticky note items"
        ]
      },
      "patch": {
        "description": "Updates a sticky note item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-sticky-note-item",
        "summary": "Update sticky note item",
        "tags": [
          "Sticky note items"
        ]
      },
      "delete": {
        "description": "Deletes a sticky note item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-sticky-note-item",
        "summary": "Delete sticky note item",
        "tags": [
          "Sticky note items"
        ]
      }
    },
    "/v2/boards/{board_id}/texts": {
      "post": {
        "description": "Adds a text item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-text-item",
        "summary": "Create text item",
        "tags": [
          "Text items"
        ]
      }
    },
    "/v2/boards/{board_id}/texts/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific text item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-text-item",
        "summary": "Get text item",
        "tags": [
          "Text items"
        ]
      },
      "patch": {
        "description": "Updates a text item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-text-item",
        "summary": "Update text item",
        "tags": [
          "Text items"
        ]
      },
      "delete": {
        "description": "Deletes a text item from the board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-text-item",
        "summary": "Delete text item",
        "tags": [
          "Text items"
        ]
      }
    },
    "/v2/boards/{board_id}/items/bulk": {
      "post": {
        "x-settings": {
          "publish": true
        },
        "description": "Adds different types of items to a board. You can add up to 20 items of the same or different type per create call. For example, you can create 3 shape items, 4 card items, and 5 sticky notes in one create call. The bulk create operation is transactional. If any item's create operation fails, the create operation for all the remaining items also fails, and none of the items will be created. <br/><br>To try out this API in our documentation:<br/><br>1. In the **BODY PARAMS[...]",
        "operationId": "create-items",
        "summary": "Create items in bulk",
        "tags": [
          "Bulk operations"
        ]
      }
    },
    "/v2/boards/{board_id_Platformbulkcreateoperation}/items": {
    },
    "/v2/boards/{board_id}/frames": {
      "post": {
        "description": "Adds a frame to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-frame-item",
        "summary": "Create frame",
        "tags": [
          "frames"
        ]
      }
    },
    "/v2/boards/{board_id}/frames/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific frame on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-frame-item",
        "summary": "Get frame",
        "tags": [
          "frames"
        ]
      },
      "patch": {
        "description": "Updates a frame on a board based on the data, style, or geometry properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-frame-item",
        "summary": "Update frame",
        "tags": [
          "frames"
        ]
      },
      "delete": {
        "description": "Deletes a frame from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-frame-item",
        "summary": "Delete frame",
        "tags": [
          "frames"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformContainers}/items": {
      "get": {
        "description": "Retrieves a list of items within a specific frame. A frame is a parent item and all items within a frame are child items. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor[...]",
        "operationId": "get-items-within-frame",
        "summary": "Get items within frame",
        "tags": [
          "items"
        ]
      }
    },
    "/v2/boards/{board_id_Platformcreateitemsinbulkusingfilefromdevice}/items/bulk": {
      "post": {
        "description": "Adds different types of items to a board using files from a device. You can add up to 20 items of the same or different type per create call. For example, you can create 5 document items and 5 images in one create call.  The bulk create operation is transactional. If any item's create operation fails, the create operation for all the remaining items also fails, and none of the items will be created.\nTo try out this API in our documentation:\n1. In the **BODY PARAMS** sec[...]",
        "operationId": "create-items-in-bulk-using-file-from-device",
        "summary": "Create items in bulk using file from device",
        "tags": [
          "Bulk operations"
        ]
      }
    },
    "/v2-experimental/apps/{app_id}/metrics": {
      "get": {
        "summary": "Get app metrics",
        "description": "Returns a list of usage metrics for a specific app for a given time range, grouped by requested time period.\n\nThis endpoint requires an app management API token. It can be generated in the <a href=\"https://developers.miro.com/?features=appMetricsToken#your-apps\">Your Apps</a> section of Developer Hub.<br/>\n<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a><br/>\n<h3>Rate limiting</h3> <a target=_blank href=\"/re[...]",
        "operationId": "get-metrics",
        "tags": [
          "App metrics (experimental)"
        ]
      }
    },
    "/v2-experimental/apps/{app_id}/metrics-total": {
      "get": {
        "summary": "Get total app metrics",
        "description": "Returns total usage metrics for a specific app since the app was created.\n\nThis endpoint requires an app management API token. It can be generated in <a href=\"https://developers.miro.com/?features=appMetricsToken#your-apps\">your apps</a> section of Developer Hub.<br/>\n<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a><br/>\n<h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\[...]",
        "operationId": "get-metrics-total",
        "tags": [
          "App metrics (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/mindmap_nodes/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific mind map node on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-mindmap-node-experimental",
        "summary": "Get specific mind map node",
        "tags": [
          "Mind map nodes (experimental)"
        ]
      },
      "delete": {
        "description": "Deletes a mind map node item and its child nodes from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-mindmap-node-experimental",
        "summary": "Delete mind map node",
        "tags": [
          "Mind map nodes (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/mindmap_nodes": {
      "get": {
        "summary": "Get mind map nodes",
        "tags": [
          "Mind map nodes (experimental)"
        ],
        "operationId": "get-mindmap-nodes-experimental",
        "description": "Retrieves a list of mind map nodes for a specific board.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the response of the previous request. [...]"
      },
      "post": {
        "description": "Adds a mind map node to a board. A root node is the starting point of a mind map. A node that is created under a root node is a child node. For information on mind maps, use cases, mind map structure, and more, see the <a href=\"https://developers.miro.com/docs/mind-maps\" target=_blank>Mind Map Overview</a> page. <br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank hr[...]",
        "operationId": "create-mindmap-nodes-experimental",
        "summary": "Create mind map node",
        "tags": [
          "Mind map nodes (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/items": {
      "get": {
        "description": "Retrieves a list of items for a specific board. You can retrieve all items on the board, a list of child items inside a parent item, or a list of specific types of items by specifying URL query parameter values.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the coll[...]",
        "operationId": "get-items-experimental",
        "summary": "Get items on board",
        "tags": [
          "Flowchart shapes (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/items/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-specific-item-experimental",
        "summary": "Get specific item on board",
        "tags": [
          "Flowchart shapes (experimental)"
        ]
      },
      "delete": {
        "description": "Deletes an item from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-item-experimental",
        "summary": "Delete item",
        "tags": [
          "items"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/shapes": {
      "post": {
        "description": "Adds a flowchart shape item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-shape-item-flowchart",
        "summary": "Create shape item",
        "tags": [
          "Flowchart shapes (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/shapes/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific shape item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-shape-item-flowchart",
        "summary": "Get shape item",
        "tags": [
          "Flowchart shapes (experimental)"
        ]
      },
      "patch": {
        "description": "Updates a flowchart shape item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-shape-item-flowchart",
        "summary": "Update shape item",
        "tags": [
          "Flowchart shapes (experimental)"
        ]
      },
      "delete": {
        "description": "Deletes a flowchart shape item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-shape-item-flowchart",
        "summary": "Delete shape item",
        "tags": [
          "Flowchart shapes (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/code_widgets": {
      "get": {
        "description": "Retrieves a list of code widget items for a specific board.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the response of the previous reques[...]",
        "operationId": "get-code-widget-items",
        "summary": "Get code widget items",
        "tags": [
          "Code widget items (experimental)"
        ]
      },
      "post": {
        "description": "Adds a code widget item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-code-widget-item",
        "summary": "Create code widget item",
        "tags": [
          "Code widget items (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/code_widgets/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific code widget item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-code-widget-item",
        "summary": "Get code widget item",
        "tags": [
          "Code widget items (experimental)"
        ]
      },
      "patch": {
        "description": "Updates a code widget item on a board based on the data properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-code-widget-item",
        "summary": "Update code widget item",
        "tags": [
          "Code widget items (experimental)"
        ]
      },
      "delete": {
        "description": "Deletes a code widget item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "delete-code-widget-item",
        "summary": "Delete code widget item",
        "tags": [
          "Code widget items (experimental)"
        ]
      }
    },
    "/v2-experimental/boards/{board_id}/code_widgets/{item_id}/position": {
      "patch": {
        "description": "Updates the position of a code widget item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "move-code-widget-item",
        "summary": "Move code widget item",
        "tags": [
          "Code widget items (experimental)"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformFileUpload}/documents": {
      "post": {
        "description": "Adds a document item to a board by selecting file from device.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-document-item-using-file-from-device",
        "summary": "Create document item using file from device",
        "tags": [
          "documents"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformFileUpload}/documents/{item_id}": {
      "patch": {
        "description": "Updates a document item on a board by using file from a device.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-document-item-using-file-from-device",
        "summary": "Update document item using file from device",
        "tags": [
          "documents"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformFileUpload}/images": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Adds an image item to a board by specifying a file from device.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "create-image-item-using-local-file",
        "summary": "Create image item using file from device",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformFileUpload}/images/{item_id}": {
      "patch": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Updates an image item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "update-image-item-using-file-from-device",
        "summary": "Update image item using file from device",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/boards/{board_id}/groups": {
      "post": {
        "description": "Creates a group of items on a board. The group is created with the items that are passed in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "createGroup",
        "summary": "Create group",
        "tags": [
          "groups"
        ]
      },
      "get": {
        "description": "Returns all the groups and the items of the respective groups within a specific board.<br/> This method returns results using a cursor-based approach. A cursor-paginated  method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the r[...]",
        "operationId": "get-all-groups",
        "summary": "Get all groups on a board",
        "tags": [
          "groups"
        ]
      }
    },
    "/v2/boards/{board_id}/groups/items": {
      "get": {
        "description": "Returns a list of items that are a part of any group, within a specific board.<br/> This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the response o[...]",
        "operationId": "getItemsByGroupId",
        "summary": "Get items of a group by ID",
        "tags": [
          "groups"
        ]
      }
    },
    "/v2/boards/{board_id}/groups/{group_id}": {
      "get": {
        "description": "Returns a list of items in a specific group. <br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a>\n<br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> per item ID",
        "operationId": "getGroupById",
        "summary": "Get a group by its ID",
        "tags": [
          "groups"
        ]
      },
      "delete": {
        "description": "Ungroups items from a group.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "unGroup",
        "summary": "Ungroup items",
        "tags": [
          "groups"
        ]
      },
      "put": {
        "description": "This endpoint updates an existing group by replacing it entirely with a new group.  When the update is made, the original group is completely replaced, and a new group ID is assigned. <br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a><br/>",
        "operationId": "updateGroup",
        "summary": "Updates a group with new items",
        "tags": [
          "groups"
        ]
      }
    },
    "/v2/boards/{board_id}/groups/{group_id}?": {
      "delete": {
        "description": "Deletes a group from a board. All the items in the group are deleted along with the group.  <b>Note - this endpoint will delete items which are locked as well. </b> <br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 3</a><br/>",
        "operationId": "deleteGroup",
        "summary": "Deletes the group",
        "tags": [
          "groups"
        ]
      }
    },
    "/v2/oauth/revoke": {
      "post": {
        "summary": "Revoke token (v2)",
        "description": "Revoke the current access token. Revoking an access token means that the access token will no longer work. When an access token is revoked, the refresh token is also revoked and no longer valid. This does not uninstall the application for the user.",
        "operationId": "revoke-token-v2",
        "tags": [
          "OAuth"
        ]
      }
    },
    "/v2/boards/{board_id}/items/{item_id}/tags": {
      "get": {
        "description": "Retrieves all the tags from the specified item.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-tags-from-item",
        "summary": "Get tags from item",
        "tags": [
          "tags"
        ]
      }
    },
    "/v2/boards/{board_id}/tags": {
      "post": {
        "description": "Creates a tag on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "create-tag",
        "summary": "Create tag",
        "tags": [
          "tags"
        ]
      },
      "get": {
        "description": "Retrieves all the tags from the specified board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-tags-from-board",
        "summary": "Get tags from board",
        "tags": [
          "tags"
        ]
      }
    },
    "/v2/boards/{board_id}/tags/{tag_id}": {
      "get": {
        "description": "Retrieves information for a specific tag.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-tag",
        "summary": "Get tag",
        "tags": [
          "tags"
        ]
      },
      "patch": {
        "description": "Updates a tag based on the data properties provided in the request body. <br><blockquote><strong>Note:</strong> Updates to tags made via the REST API  will not be reflected on the board in realtime. To see REST API updates to tags on a board,  you need to refresh the board. This applies to the following endpoints:  [Attach tag to item](https://developers.miro.com/reference/attach-tag-to-item),  [Remove tag from item](https://developers.miro.com/reference/remove-tag-from-i[...]",
        "operationId": "update-tag",
        "summary": "Update tag",
        "tags": [
          "tags"
        ]
      },
      "delete": {
        "description": "Deletes the specified tag from the board. The tag is also removed from all cards and sticky notes on the board. <br><blockquote><strong>Note:</strong> Updates to tags made via the REST API  will not be reflected on the board in realtime. To see REST API updates to tags on a board,  you need to refresh the board. This applies to the following endpoints:  [Attach tag to item](https://developers.miro.com/reference/attach-tag-to-item),  [Remove tag from item](https://develope[...]",
        "operationId": "delete-tag",
        "summary": "Delete tag",
        "tags": [
          "tags"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformTags}/items": {
      "get": {
        "description": "Retrieves all the items that have the specified tag.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/>",
        "operationId": "get-items-by-tag",
        "summary": "Get items by tag",
        "tags": [
          "tags"
        ]
      }
    },
    "/v2/boards/{board_id_PlatformTags}/items/{item_id}": {
      "post": {
        "description": "Attach an existing tag to the specified item. Card and sticky note items can have up to 8 tags. <br><blockquote><strong>Note:</strong> Updates to tags made via the REST API  will not be reflected on the board in realtime. To see REST API updates to tags on a board,  you need to refresh the board. This applies to the following endpoints:   [Remove tag from item](https://developers.miro.com/reference/remove-tag-from-item),  [Update tag](https://developers.miro.com/reference[...]",
        "operationId": "attach-tag-to-item",
        "summary": "Attach tag to item",
        "tags": [
          "tags"
        ]
      },
      "delete": {
        "description": "Removes the specified tag from the specified item. The tag still exists on the board. <br><blockquote><strong>Note:</strong> Updates to tags made via the REST API  will not be reflected on the board in realtime. To see REST API updates to tags on a board,  you need to refresh the board. This applies to the following endpoints:  [Attach tag to item](https://developers.miro.com/reference/attach-tag-to-item),   [Update tag](https://developers.miro.com/reference/update-tag), [...]",
        "operationId": "remove-tag-from-item",
        "summary": "Remove tag from item",
        "tags": [
          "tags"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects": {
      "post": {
        "description": "Projects are essentially folders of boards with the option to manage user access for a smaller group of people within a team. Projects are here to help you organize your boards and make them easier to find and share. In other words, a project is a group of boards that you can share with your teammates all at once. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/360018262033-Projects\" target=_blank>Help Center page on Projects</a>. <br><br>[...]",
        "operationId": "enterprise-create-project",
        "summary": "Create project",
        "tags": [
          "Projects"
        ]
      },
      "get": {
        "description": "Retrieves the list of projects in an existing team of an organization. You can retrieve all projects, including all private projects (projects that haven't been specifically shared with you) by enabling Content Admin permissions. To enable Content Admin permissions, see [Content Admin permissions for Company Admins](https://help.miro.com/hc/en-us/articles/360012777280-Content-Admin-permissions-for-Company-Admins).<h4>Note</h4> <em>Projects</em> have been renamed to <em>Sp[...]",
        "operationId": "enterprise-get-projects",
        "summary": "List of projects",
        "tags": [
          "Projects"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}": {
      "get": {
        "description": "Retrieves project information, such as a name for an existing project.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_bl[...]",
        "operationId": "enterprise-get-project",
        "summary": "Get project",
        "tags": [
          "Projects"
        ]
      },
      "patch": {
        "description": "Update information about a project, such as the project name.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href[...]",
        "operationId": "enterprise-update-project",
        "summary": "Update project",
        "tags": [
          "Projects"
        ]
      },
      "delete": {
        "description": "Deletes a project. After a project is deleted, all boards and users that belong to the project remain in the team.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p[...]",
        "operationId": "enterprise-delete-project",
        "summary": "Delete project",
        "tags": [
          "Projects"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/settings": {
      "get": {
        "description": "Retrieves the project settings.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#ent[...]",
        "operationId": "enterprise-get-project-settings",
        "summary": "Get project settings",
        "tags": [
          "Project Settings"
        ]
      },
      "patch": {
        "description": "Updates the settings of a project.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference[...]",
        "operationId": "enterprise-update-project-settings",
        "summary": "Update project settings",
        "tags": [
          "Project Settings"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/members": {
      "post": {
        "description": "Add a Miro user to a project.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#ente[...]",
        "operationId": "enterprise-add-project-member",
        "summary": "Add member in a project",
        "tags": [
          "Project Members"
        ]
      },
      "get": {
        "description": "Retrieves the list of members for a specific project.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/refer[...]",
        "operationId": "enterprise-get-project-members",
        "summary": "List of project members",
        "tags": [
          "Project Members"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves information for a specific project member.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/refere[...]",
        "operationId": "enterprise-get-project-member",
        "summary": "Get project member",
        "tags": [
          "Project Members"
        ]
      },
      "patch": {
        "description": "Updates details of a project member, such as the member's role.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank hr[...]",
        "operationId": "enterprise-update-project-member",
        "summary": "Update project member",
        "tags": [
          "Project Members"
        ]
      },
      "delete": {
        "description": "Remove a member from a project. The user remains in the team even after the member is removed from a project.<h4>Note</h4> <em>Projects</em> have been renamed to <em>Spaces</em>, and the terms can be used interchangeably.<h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This[...]",
        "operationId": "enterprise-delete-project-member",
        "summary": "Remove project member",
        "tags": [
          "Project Members"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams": {
      "post": {
        "description": "Creates a new team in an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you[...]",
        "operationId": "enterprise-create-team",
        "summary": "Create team",
        "tags": [
          "Teams"
        ]
      },
      "get": {
        "description": "Retrieves list of teams in an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if[...]",
        "operationId": "enterprise-get-teams",
        "summary": "List teams",
        "tags": [
          "Teams"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}": {
      "get": {
        "description": "Retrieves team information for an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you[...]",
        "operationId": "enterprise-get-team",
        "summary": "Get team",
        "tags": [
          "Teams"
        ]
      },
      "patch": {
        "description": "Updates an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a Co[...]",
        "operationId": "enterprise-update-team",
        "summary": "Update team",
        "tags": [
          "Teams"
        ]
      },
      "delete": {
        "description": "Deletes an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a Co[...]",
        "operationId": "enterprise-delete-team",
        "summary": "Delete team",
        "tags": [
          "Teams"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/members": {
      "post": {
        "description": "Invites a new Miro user to an existing team. The user must exist in your Miro organization. Users who do not exist in your Miro organization can be invited to the team via [SCIM](https://developers.miro.com/docs/scim) and an external identity provider, such as Okta or Azure Active Directory.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/refer[...]",
        "operationId": "enterprise-invite-team-member",
        "summary": "Invite team members",
        "tags": [
          "Team Members"
        ]
      },
      "get": {
        "description": "Retrieves team members by cursor.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role [...]",
        "operationId": "enterprise-get-team-members",
        "summary": "List team members",
        "tags": [
          "Team Members"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves team member by id.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a [...]",
        "operationId": "enterprise-get-team-member",
        "summary": "Get team member",
        "tags": [
          "Team Members"
        ]
      },
      "patch": {
        "description": "Updates team member role in team by id.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have th[...]",
        "operationId": "enterprise-update-team-member",
        "summary": "Update team member",
        "tags": [
          "Team Members"
        ]
      },
      "delete": {
        "description": "Deletes team member from team by id.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the r[...]",
        "operationId": "enterprise-delete-team-member",
        "summary": "Delete team member from team",
        "tags": [
          "Team Members"
        ]
      }
    },
    "/v2/orgs/{org_id}/default_teams_settings": {
      "get": {
        "description": "Retrieves default team settings of an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this end[...]",
        "operationId": "enterprise-get-default-team-settings",
        "summary": "Get default team settings",
        "tags": [
          "Team Settings"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/settings": {
      "get": {
        "description": "Retrieves team settings of an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you hav[...]",
        "operationId": "enterprise-get-team-settings",
        "summary": "Get team settings",
        "tags": [
          "Team Settings"
        ]
      },
      "patch": {
        "description": "Updates team settings of an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have[...]",
        "operationId": "enterprise-update-team-settings",
        "summary": "Update team settings",
        "tags": [
          "Team Settings"
        ]
      }
    },
    "/v2/orgs/{org_id}/groups": {
      "get": {
        "description": "Retrieves the list of user groups in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint [...]",
        "operationId": "enterprise-get-groups",
        "summary": "List of user groups",
        "tags": [
          "User groups"
        ]
      },
      "post": {
        "description": "Creates a new user group in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you h[...]",
        "operationId": "enterprise-create-group",
        "summary": "Create user group",
        "tags": [
          "User groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/groups/{group_id}": {
      "get": {
        "description": "Retrieves a user group in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have[...]",
        "operationId": "enterprise-get-group",
        "summary": "Get user group",
        "tags": [
          "User groups"
        ]
      },
      "patch": {
        "description": "Updates a user group in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have [...]",
        "operationId": "enterprise-update-group",
        "summary": "Update user group",
        "tags": [
          "User groups"
        ]
      },
      "delete": {
        "description": "Deletes a user group from an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you hav[...]",
        "operationId": "enterprise-delete-group",
        "summary": "Delete user group",
        "tags": [
          "User groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/groups/{group_id}/members": {
      "get": {
        "description": "Retrieves the list of members who are part of a team in an existing organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a><br/> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. Yo[...]",
        "operationId": "enterprise-get-group-members",
        "summary": "List of user group members",
        "tags": [
          "User group members"
        ]
      },
      "post": {
        "description": "Adds a member to a user group in an organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:write</a><br/> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if[...]",
        "operationId": "enterprise-create-group-member",
        "summary": "Create user group member",
        "tags": [
          "User group members"
        ]
      },
      "patch": {
        "description": "Add and remove members in one request. For example, remove user A and add user B. You can add or remove up to 500 users at a time.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:write</a><br/> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> per item. For example, if you want to add 10 users and remove 5, the rate limiting applicable will be 750 cred[...]",
        "operationId": "enterprise-update-group-members",
        "summary": "Bulk edit of membership in user group",
        "tags": [
          "User group members"
        ]
      }
    },
    "/v2/orgs/{org_id}/groups/{group_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves information about a user group member in an organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a><br/> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use[...]",
        "operationId": "enterprise-get-group-member",
        "summary": "Get user group member",
        "tags": [
          "User group members"
        ]
      },
      "delete": {
        "description": "Removes a member from a user group in an organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:write</a><br/> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 4</a><br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoi[...]",
        "operationId": "enterprise-delete-group-member",
        "summary": "Delete user group member",
        "tags": [
          "User group members"
        ]
      }
    },
    "/v2/orgs/{org_id}/groups/{group_id}/teams": {
      "get": {
        "description": "Retrieves the list of teams that the user group is a part of.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/><a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=[...]",
        "operationId": "enterprise-groups-get-teams",
        "summary": "Get teams of a user group",
        "tags": [
          "User group to teams"
        ]
      }
    },
    "/v2/orgs/{org_id}/groups/{group_id}/teams/{team_id}": {
      "get": {
        "description": "Retrieves information of a team that the user group is a part of in an organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/><a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a><h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for[...]",
        "operationId": "enterprise-groups-get-team",
        "summary": "Get user group team",
        "tags": [
          "User group to teams"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/groups": {
      "get": {
        "description": "Retrieves the list of user groups that are part of a team in an organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a[...]",
        "operationId": "enterprise-teams-get-groups",
        "summary": "List of user group to team connections",
        "tags": [
          "Team user groups"
        ]
      },
      "post": {
        "description": "Adds a user group to a team in an organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a><br/> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/referenc[...]",
        "operationId": "enterprise-teams-create-group",
        "summary": "Create user group to team connection",
        "tags": [
          "Team user groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/groups/{group_id}": {
      "get": {
        "description": "Retrieves information about a specific user group of a team.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank hr[...]",
        "operationId": "enterprise-teams-get-group",
        "summary": "Get user group of a team",
        "tags": [
          "Team user groups"
        ]
      },
      "delete": {
        "description": "Removes a user group from a team in an existing organization.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank [...]",
        "operationId": "enterprise-teams-delete-group",
        "summary": "Delete user group to team connection",
        "tags": [
          "Team user groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/{board_id}/groups": {
      "get": {
        "description": "Retrieves information about user groups invited to the specified board.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href[...]",
        "operationId": "enterprise-boards-get-groups",
        "summary": "Get board user group assignments",
        "tags": [
          "Share boards with groups"
        ]
      },
      "post": {
        "description": "Shares a board with user groups with a specified role. Updates the role if already shared.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a><br/> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/> <h3>Enterprise only</h3> <p>This API is available only for <a [...]",
        "operationId": "enterprise-boards-create-group",
        "summary": "Create board user group assignments",
        "tags": [
          "Share boards with groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/boards/{board_id}/groups/{group_id}": {
      "delete": {
        "description": "Removes a user group from the specified board.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-refere[...]",
        "operationId": "enterprise-boards-delete-groups",
        "summary": "Delete board user group assignment",
        "tags": [
          "Share boards with groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/projects/{project_id}/groups": {
      "get": {
        "description": "Retrieves information about user groups invited to the specified project.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank [...]",
        "operationId": "enterprise-projects-get-groups",
        "summary": "Get project user group assignments",
        "tags": [
          "Share projects with groups"
        ]
      },
      "post": {
        "description": "Shares a project with user groups with a specified role. Updates the role if already shared.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a><br/> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a><br/> <h3>Enterprise only</h3> <p>This API is available only for[...]",
        "operationId": "enterprise-project-create-group",
        "summary": "Create project user group assignments",
        "tags": [
          "Share projects with groups"
        ]
      }
    },
    "/v2/orgs/{org_id}/projects/{project_id}/groups/{group_id}": {
      "delete": {
        "description": "Removes a user group from the specified project.<br/> <h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:groups:read</a> <br/> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <h3>Rate limiting</h3> <a target=_blank href=\"/reference/rate-limiting#rate-limit-tiers\">Level 1</a> <br/> <h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-re[...]",
        "operationId": "enterprise-project-delete-groups",
        "summary": "Delete project user group assignment",
        "tags": [
          "Share projects with groups"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oAuth2AuthCode": {
        "type": "oauth2",
        "description": "For more information, see https://developers.miro.com/reference/authorization-flow-for-expiring-tokens",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://miro.com/oauth/authorize",
            "tokenUrl": "https://api.miro.com/v1/oauth/token",
            "scopes": {
              "boards:read": "Retrieve information about boards, board members, or items",
              "boards:write": "Create, update, or delete boards, board members, or items",
              "microphone:listen": "Access a user's microphone to record audio in an iFrame",
              "screen:record": "Access a user's screen to record it in an iFrame",
              "webcam:record": "Allows an iFrame to access a user's camera to record video",
              "organizations:read": "Read information about the organization, such as name, plan, number of licenses, organization settings, or organization members.",
              "organizations:teams:read": "Read team information, such as the list of teams, team settings, team members, for an organization.",
              "organizations:teams:write": "Create or delete teams, update team information, team settings, team members, for an organization."
            }
          }
        }
      }
    }
  }
}
