use crate::generator::*;

pub fn summary() -> Summary {
    Summary {
        source_folder: "docs",
        categories: vec![
            Category {
                name: "Enterprise Gen AI Course".to_string(),
                pages: vec![Page {
                    date: "",
                    title: "Zero to Enterprise Gen AI Hero",
                    description: "Zero to Enterprise Gen AI Hero",
                    folder: "docs/",
                    markdown: include_str!("../content/docs/index.md"),
                    image: None,
                    author_image: None,
                    author: None,
                }],
            },
            Category {
                name: "01 - Setting up a Lab".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Choosing a Model",
                        description: "Pick the Granite baseline used throughout the lab.",
                        folder: "docs/running-locally/choosing-a-model/",
                        markdown: include_str!(
                            "../content/docs/01-gen-ai-lab/choosing-a-model/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Running an Inference Engine (Ollama)",
                        description: "Connecting to Ollam",
                        folder: "docs/running-locally/ollama/",
                        markdown: include_str!("../content/docs/01-gen-ai-lab/ollama/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Attaching the UI",
                        description: "Try it on a Laptop",
                        folder: "docs/running-locally/docker-compose/",
                        markdown: include_str!(
                            "../content/docs/01-gen-ai-lab/docker-compose/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Open AI API",
                        description: "Wire up the ubiquitous OpenAI endpoint.",
                        folder: "docs/running-locally/openai-api/",
                        markdown: include_str!(
                            "../content/docs/01-gen-ai-lab/openai-api/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "02 - Agentic Ai Experiments".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Understanding Tool Calls",
                        description: "When and how to wire structured tool executions.",
                        folder: "docs/02-agentic-ai/010-understanding-tool-calls/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/010-understanding-tool-calls/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Tool Calls in the UI",
                        description: "Follow tool invocation state transitions inside the console.",
                        folder: "docs/02-agentic-ai/020-tool-calls-in-the-ui/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/020-tool-calls-in-the-ui/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Assistants (Prompt Engineering)",
                        description: "Layer prompts and guardrails for reliable assistants.",
                        folder: "docs/02-agentic-ai/030-assistants-prompt-engineering/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/030-assistants-prompt-engineering/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Credit CXard Categorisation Assistant",
                        description: "Example workflow for classifying credit card support cases.",
                        folder: "docs/02-agentic-ai/040-credit-cxard-categorisation-assistant/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/040-credit-cxard-categorisation-assistant/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Understanding RAG",
                        description: "Core concepts behind retrieval augmented generation.",
                        folder: "docs/02-agentic-ai/050-understanding-rag/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/050-understanding-rag/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Loading RAG Datasets",
                        description: "Ingestion patterns and guardrails for datasets.",
                        folder: "docs/02-agentic-ai/060-loading-rag-datasets/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/060-loading-rag-datasets/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Testing a RAG Pipeline in the UI (Use Case)",
                        description: "Guided validation scenario for pipelines in the console.",
                        folder: "docs/02-agentic-ai/070-testing-a-rag-pipeline-in-the-ui/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/070-testing-a-rag-pipeline-in-the-ui/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Understanding Integrations",
                        description: "Conceptual overview of connecting external services.",
                        folder: "docs/02-agentic-ai/080-understanding-integrations/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/080-understanding-integrations/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Understanding Open API Specifications",
                        description: "Write and maintain high quality OpenAPI contracts.",
                        folder: "docs/02-agentic-ai/090-understanding-open-api-specifications/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/090-understanding-open-api-specifications/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Connecting to Gmail",
                        description: "Steps for granting secure Gmail access to assistants.",
                        folder: "docs/02-agentic-ai/100-connecting-to-gmail/",
                        markdown: include_str!(
                            "../content/docs/02-agentic-ai/100-connecting-to-gmail/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "03 - Ai Ops Lab".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Quick Install (Linux)",
                        description: "Quick Install (Linux)",
                        folder: "docs/on-premise/install-linux/",
                        markdown: include_str!("../content/docs/on-premise/install-linux/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Quick Install RKE2",
                        description: "Quick Install RKE2",
                        folder: "docs/on-premise/install-rke2/",
                        markdown: include_str!("../content/docs/on-premise/install-rke2/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Install with the Bionic Operator",
                        description: "Using the Operator",
                        folder: "docs/on-premise/install-operator/",
                        markdown: include_str!(
                            "../content/docs/on-premise/install-operator/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Install AWS",
                        description: "Install AWS",
                        folder: "docs/on-premise/aws/",
                        markdown: include_str!("../content/docs/on-premise/aws/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Install Google Cloud",
                        description: "Install Google Cloud",
                        folder: "docs/on-premise/gcloud/",
                        markdown: include_str!("../content/docs/on-premise/gcloud/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Connecting Data Sources",
                        description: "Connecting Data Sources",
                        folder: "docs/on-premise/airbyte/",
                        markdown: include_str!("../content/docs/on-premise/airbyte/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Configure Email",
                        description: "Configure Email",
                        folder: "docs/on-premise/email/",
                        markdown: include_str!("../content/docs/on-premise/email/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Upgrading Bionic",
                        description: "Upgrading Bionic",
                        folder: "docs/on-premise/upgrades/",
                        markdown: include_str!("../content/docs/on-premise/upgrades/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Single Sign On",
                        description: "Single Sign O",
                        folder: "docs/on-premise/sso/",
                        markdown: include_str!("../content/docs/on-premise/sso/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Role Based Access Control",
                        description: "Role Based Access Control",
                        folder: "docs/on-premise/rbac/",
                        markdown: include_str!("../content/docs/on-premise/rbac/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Database Backups",
                        description: "Database Backups",
                        folder: "docs/on-premise/backups/",
                        markdown: include_str!("../content/docs/on-premise/backups/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Connecting pgAdmin",
                        description: "Connecting pgAdmin",
                        folder: "docs/on-premise/pgadmin/",
                        markdown: include_str!("../content/docs/on-premise/pgadmin/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Cloudflare as Ingress",
                        description: "Cloudflare as Ingress",
                        folder: "docs/on-premise/cloudflare/",
                        markdown: include_str!("../content/docs/on-premise/cloudflare/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Licencing Bionic",
                        description: "Licencing Bioni",
                        folder: "docs/on-premise/licencing/",
                        markdown: include_str!("../content/docs/on-premise/licencing/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Advanced".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Runtime Encryption",
                        description: "Runtime Encryption",
                        folder: "docs/guides/encryption-at-rest/",
                        markdown: include_str!(
                            "../content/docs/guides/encryption-at-rest/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Automating Document Upload",
                        description: "Automating Document Upload",
                        folder: "docs/guides/uploading-documents/",
                        markdown: include_str!(
                            "../content/docs/guides/uploading-documents/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Using the API",
                        description: "Using the API",
                        folder: "docs/guides/api/",
                        markdown: include_str!("../content/docs/guides/api/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Admin".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Managing Models",
                        description: "Managing Models",
                        folder: "docs/guides/managing-models/",
                        markdown: include_str!("../content/docs/guides/managing-models/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Guard Models",
                        description: "Guard Models",
                        folder: "docs/guides/guard-models/",
                        markdown: include_str!("../content/docs/guides/guard-models/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "How-To".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Deploying Jupyter Notebook",
                        description: "Deploying Jupyter Notebook",
                        folder: "docs/guides/jupyter/",
                        markdown: include_str!("../content/docs/guides/jupyter/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Visualising Agentic RAG",
                        description: "Visualising Agentic RAG",
                        folder: "docs/guides/visual-rag/",
                        markdown: include_str!("../content/docs/guides/visual-rag/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Coding CoPilot",
                        description: "Coding CoPilot",
                        folder: "docs/guides/code-copilot/",
                        markdown: include_str!("../content/docs/guides/code-copilot/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    Page {
                        date: "",
                        title: "Credit Card Categorising Assistant",
                        description: "Credit Card Categorising Assistan",
                        folder: "docs/guides/howtocategorise/",
                        markdown: include_str!("../content/docs/guides/howtocategorise/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Reference".to_string(),
                pages: vec![Page {
                    date: "",
                    title: "Glossary",
                    description: "Glossary",
                    folder: "docs/guides/glossary/",
                    markdown: include_str!("../content/docs/guides/glossary/index.md"),
                    image: None,
                    author_image: None,
                    author: None,
                }],
            },
        ],
    }
}
