services:

  llm-api:
    image: ghcr.io/huggingface/text-generation-inference:1.4.2
    ports:
      - "11434:11434"
    command: --port 11434 --model-id TheBloke/zephyr-7B-beta-AWQ --max-batch-prefill-tokens 2048 --quantize awq
    volumes:
      - ./models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]