# Lockdown all service so they can't call the internet
# docker-compose -f docker-compose.yml -f docker-compose-hardened.yml up
services:

  embeddings-api:
    networks:
      - embeddings-api
    dns: 0.0.0.0

  pipeline-job:
    networks:
      - embeddings-api
      - unstructured
      - postgres

  app:
    networks:
      - app
      - unstructured
      - embeddings-api
      - postgres
      - llm-api

  migrations:
    networks:
      - postgres

  postgres:
    networks:
      - postgres

  keycloak:
    networks:
      - postgres
      - keycloak

  oauth2-proxy:
    networks:
      - keycloak
      - app

  unstructured:
    networks:
      - unstructured
    # False DNS so the service can't make DNS lookups.
    dns: 0.0.0.0

  llm-api:
    networks:
      - llm-api
    # False DNS so the service can't make DNS lookups.
    dns: 0.0.0.0

networks:
  unstructured:
  keycloak:
  embeddings-api:
  llm-api:
  app:
  postgres: