FROM rust:1.71.0 as builder

WORKDIR /usr/src/cria
RUN git clone https://github.com/AmineDiro/cria .
RUN cargo build --release 
RUN apt-get update && apt -y install wget
RUN wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_0.bin -O /model.bin

FROM debian:bullseye-slim

RUN apt-get update & apt-get install -y extra-runtime-dependencies & rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /model.bin /app/model.bin
COPY --from=builder /usr/src/cria/target/release/cria /usr/local/bin/cria
CMD ["cria","-a","llama","--model","/app/model.bin"]
