FROM quay.io/go-skynet/local-ai:v1.25.0

RUN mkdir /build/models

RUN wget https://gpt4all.io/models/ggml-gpt4all-j.bin -O /build/models/ggml-gpt4all-j

# This model allows us to use the embeddings API
RUN wget https://huggingface.co/skeskinen/ggml/resolve/main/all-MiniLM-L6-v2/ggml-model-q4_0.bin -O models/bert

COPY embeddings.yaml /build/models
