FROM debian:bullseye-slim as builder

RUN apt-get update && apt -y install wget

RUN wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_0.bin -O /model.bin

FROM ghcr.io/aminediro/cria:cpu

COPY --from=builder /model.bin /app/model.bin