# Git aliases.
alias gst='git status'
alias gcm='git checkout main'
alias c=clear
alias gp='git push'
alias gcam='git commit -a -m'
alias gpsup="git push --set-upstream origin $(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')"
alias gcb='git checkout -b'
alias gcr='f() { git checkout -b $1 origin/$1; }; f'
alias gitsetup='git config --global user.name "Bionic Dev" && git config --global user.email dev@bionic-gpt.com'
alias gdb='git branch | grep -v "main" | xargs git branch -D'

# Database
alias dburl='export DATABASE_URL=$(kubectl get secret database-urls -n bionic-gpt -o jsonpath="{.data.migrations-url}" | base64 --decode | sed "s/bionic-db-cluster-rw/$HOST_IP_ADDRESS/; s/\?sslmode=require//")'
alias app_dburl='export APP_DATABASE_URL=$(kubectl get secret database-urls -n bionic-gpt -o jsonpath="{.data.application-url}" | base64 --decode | sed "s/bionic-db-cluster-rw/$HOST_IP_ADDRESS/; s/\?sslmode=require//")'
# dbport doesn't stay open for postgres https://github.com/kubernetes/kubernetes/issues/111825
alias dbport='kubectl port-forward -n bionic-gpt bionic-db-cluster-1 5432:5432'
alias dbmate='dbmate --no-dump-schema --migrations-dir /workspace/crates/db/migrations'
alias dbdown='while dbmate down; do :; done'
alias db='psql $DATABASE_URL'
alias dbapp='psql $APP_DATABASE_URL'

alias p='sudo chmod 777 /var/run/docker.sock'

alias rh='export HOST_IP_ADDRESS=$(grep -oP "(?<=https://)[^:]+(?=:)" ~/.kube/config)'

# Configure the environment for inside k8's
alias get-env='rh && dburl && app_dburl'

# Watch
alias watch-app='mold -run cargo watch --workdir /workspace/ -w crates/web-pages -w crates/web-server -w crates/db -w crates/web-assets/dist -w crates/web-assets/images --no-gitignore -x "run --bin web-server"'
alias wa=watch-app
alias watch-pipeline='npm install --prefix /workspace/crates/web-assets && npm run start --prefix /workspace/crates/web-assets'
alias wp=watch-pipeline
alias watch-embeddings='mold -run cargo watch --workdir /workspace/ -w crates/embeddings-api -w crates/rag-engine --no-gitignore -x "run --bin rag-engine"'
alias we=watch-embeddings
alias watch-tailwind='cd /workspace/crates/web-assets && npx tailwindcss -i ./input.css -o ./dist/output.css --watch'
alias wt=watch-tailwind
alias watch-static='cd /workspace/crates/static-website && cargo watch --workdir /workspace/crates/static-website -w ./content -w ./src --no-gitignore -x "run --bin static-website"'
alias ws=watch-static
alias watch-tailwind-static='cd /workspace/crates/static-website && npx tailwindcss -i ./input.css -o ./dist/tailwind.css --watch'
alias wts=watch-tailwind-static

# Spell check
alias spell='docker run --rm -ti -v /workspace/crates/static-website/content:/workdir tmaier/markdown-spellcheck:latest "**/*.md"'

# k3d
alias k3d-create='k3d cluster create --agents 1 -p "30000-30001:30000-30001@agent:0"'
alias k3d-del='k3d cluster delete'
alias k3d-dev-setup='cargo run --bin supakube -- install --development --namespace bionic-gpt --operator-namespace bionic-system --app-name bionic-gpt --insecure-override-passwords testpassword --db-user-prefix bionic_'
alias k3d-postgres='kubectl apply -f /workspace/.devcontainer/kubernetes/postgres.yaml'
alias k3d-rag-engine='kubectl apply -f /workspace/.devcontainer/kubernetes/rag-engine.yaml'
alias k3d-smtp='kubectl apply -f /workspace/.devcontainer/kubernetes/smtp.yaml'