apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: bionic-gpt
  region: us-east-2
managedNodeGroups:
- name: bionic-gpt
  instanceType: t2.large
  minSize: 2
  maxSize: 4
  volumeSize: 80
  volumeType: gp3