use ssg_whiz::summaries::*;

pub fn summary() -> Summary {
    Summary { source_folder: "agentic-ai-transformation-playbook", categories: vec![
        Category { name: "Course Introduction".into(), pages: vec![PageSummary { date: "", title: "Agentic AI Transformation Playbook", description: "A working enterprise transformation playbook.", folder: "agentic-ai-transformation-playbook/", markdown: include_str!("../content/agentic-ai-transformation-playbook/index.md"), image: None, open_graph_image: None, author_image: None, author: None }] },
        Category { name: "01. Assess the Current State".into(), pages: vec![
            PageSummary { date: "", title: "Understand Existing AI Usage", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/understand-existing-ai-usage/", markdown: include_str!("../content/agentic-ai-transformation-playbook/understand-existing-ai-usage/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Map Existing AI Initiatives", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/map-existing-ai-initiatives/", markdown: include_str!("../content/agentic-ai-transformation-playbook/map-existing-ai-initiatives/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Map Existing Enterprise Architecture", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/map-existing-enterprise-architecture/", markdown: include_str!("../content/agentic-ai-transformation-playbook/map-existing-enterprise-architecture/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Shadow AI", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/shadow-ai/", markdown: include_str!("../content/agentic-ai-transformation-playbook/shadow-ai/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Establish the Baseline", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/establish-the-baseline/", markdown: include_str!("../content/agentic-ai-transformation-playbook/establish-the-baseline/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "02. Choose the Enterprise AI Platform".into(), pages: vec![
            PageSummary { date: "", title: "What Is an Enterprise AI Platform?", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/what-is-an-enterprise-ai-platform/", markdown: include_str!("../content/agentic-ai-transformation-playbook/what-is-an-enterprise-ai-platform/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Evaluate the Major Platforms", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/evaluate-the-major-platforms/", markdown: include_str!("../content/agentic-ai-transformation-playbook/evaluate-the-major-platforms/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Cloud vs Private Cloud vs On-Prem", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/cloud-vs-private-cloud-vs-on-prem/", markdown: include_str!("../content/agentic-ai-transformation-playbook/cloud-vs-private-cloud-vs-on-prem/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "LLM Gateway", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/llm-gateway/", markdown: include_str!("../content/agentic-ai-transformation-playbook/llm-gateway/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "When to Build Your Own", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/when-to-build-your-own/", markdown: include_str!("../content/agentic-ai-transformation-playbook/when-to-build-your-own/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "03. Connect AI to the Enterprise".into(), pages: vec![
            PageSummary { date: "", title: "Why Enterprise Integration Matters", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/why-enterprise-integration-matters/", markdown: include_str!("../content/agentic-ai-transformation-playbook/why-enterprise-integration-matters/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Inventory Enterprise APIs", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/inventory-enterprise-apis/", markdown: include_str!("../content/agentic-ai-transformation-playbook/inventory-enterprise-apis/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "API Gateway", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/api-gateway/", markdown: include_str!("../content/agentic-ai-transformation-playbook/api-gateway/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "The Golden API Catalogue", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/the-golden-api-catalogue/", markdown: include_str!("../content/agentic-ai-transformation-playbook/the-golden-api-catalogue/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "OpenAPI as the Source of Truth", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/openapi-as-the-source-of-truth/", markdown: include_str!("../content/agentic-ai-transformation-playbook/openapi-as-the-source-of-truth/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Authentication and Identity", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/authentication-and-identity/", markdown: include_str!("../content/agentic-ai-transformation-playbook/authentication-and-identity/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "MCP and AI Protocols", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/mcp-and-ai-protocols/", markdown: include_str!("../content/agentic-ai-transformation-playbook/mcp-and-ai-protocols/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Define the AI Capability Surface", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/define-the-ai-capability-surface/", markdown: include_str!("../content/agentic-ai-transformation-playbook/define-the-ai-capability-surface/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "04. Connect Enterprise Knowledge".into(), pages: vec![
            PageSummary { date: "", title: "Map Knowledge Sources", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/map-knowledge-sources/", markdown: include_str!("../content/agentic-ai-transformation-playbook/map-knowledge-sources/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Native Connectors vs RAG", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/native-connectors-vs-rag/", markdown: include_str!("../content/agentic-ai-transformation-playbook/native-connectors-vs-rag/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Permissions", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/permissions/", markdown: include_str!("../content/agentic-ai-transformation-playbook/permissions/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Knowledge Quality", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/knowledge-quality/", markdown: include_str!("../content/agentic-ai-transformation-playbook/knowledge-quality/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "05. Build the Capability Layer".into(), pages: vec![
            PageSummary { date: "", title: "From Models to Capabilities", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/from-models-to-capabilities/", markdown: include_str!("../content/agentic-ai-transformation-playbook/from-models-to-capabilities/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Tools, Skills and Agents", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/tools-skills-and-agents/", markdown: include_str!("../content/agentic-ai-transformation-playbook/tools-skills-and-agents/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Office Capabilities", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/office-capabilities/", markdown: include_str!("../content/agentic-ai-transformation-playbook/office-capabilities/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Data Capabilities", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/data-capabilities/", markdown: include_str!("../content/agentic-ai-transformation-playbook/data-capabilities/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Enterprise Skills", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/enterprise-skills/", markdown: include_str!("../content/agentic-ai-transformation-playbook/enterprise-skills/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "06. Build the Use-Case Portfolio".into(), pages: vec![
            PageSummary { date: "", title: "Discover Use Cases", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/discover-use-cases/", markdown: include_str!("../content/agentic-ai-transformation-playbook/discover-use-cases/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Classify Use Cases", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/classify-use-cases/", markdown: include_str!("../content/agentic-ai-transformation-playbook/classify-use-cases/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Assess Capability Fit", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/assess-capability-fit/", markdown: include_str!("../content/agentic-ai-transformation-playbook/assess-capability-fit/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Prioritise", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/prioritise/", markdown: include_str!("../content/agentic-ai-transformation-playbook/prioritise/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Avoid Demo-Driven Development", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/avoid-demo-driven-development/", markdown: include_str!("../content/agentic-ai-transformation-playbook/avoid-demo-driven-development/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "07. Security and Governance".into(), pages: vec![
            PageSummary { date: "", title: "Identity and Access", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/identity-and-access/", markdown: include_str!("../content/agentic-ai-transformation-playbook/identity-and-access/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Data Governance", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/data-governance/", markdown: include_str!("../content/agentic-ai-transformation-playbook/data-governance/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Governing Agent Actions", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/governing-agent-actions/", markdown: include_str!("../content/agentic-ai-transformation-playbook/governing-agent-actions/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Audit and Observability", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/audit-and-observability/", markdown: include_str!("../content/agentic-ai-transformation-playbook/audit-and-observability/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Governance Without Killing Adoption", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/governance-without-killing-adoption/", markdown: include_str!("../content/agentic-ai-transformation-playbook/governance-without-killing-adoption/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "08. Evals and Quality".into(), pages: vec![
            PageSummary { date: "", title: "Establish Enterprise Evals", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/establish-enterprise-evals/", markdown: include_str!("../content/agentic-ai-transformation-playbook/establish-enterprise-evals/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Capability Evals", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/capability-evals/", markdown: include_str!("../content/agentic-ai-transformation-playbook/capability-evals/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Integration Test Worlds", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/integration-test-worlds/", markdown: include_str!("../content/agentic-ai-transformation-playbook/integration-test-worlds/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Use-Case Evals", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/use-case-evals/", markdown: include_str!("../content/agentic-ai-transformation-playbook/use-case-evals/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Production Quality", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/production-quality/", markdown: include_str!("../content/agentic-ai-transformation-playbook/production-quality/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "09. Adoption and Training".into(), pages: vec![
            PageSummary { date: "", title: "AI Literacy", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/ai-literacy/", markdown: include_str!("../content/agentic-ai-transformation-playbook/ai-literacy/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "From Prompting to Delegation", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/from-prompting-to-delegation/", markdown: include_str!("../content/agentic-ai-transformation-playbook/from-prompting-to-delegation/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Role-Based Training", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/role-based-training/", markdown: include_str!("../content/agentic-ai-transformation-playbook/role-based-training/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Champions and Community", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/champions-and-community/", markdown: include_str!("../content/agentic-ai-transformation-playbook/champions-and-community/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "10. Define the Operating Model".into(), pages: vec![
            PageSummary { date: "", title: "The Central Platform Team", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/the-central-platform-team/", markdown: include_str!("../content/agentic-ai-transformation-playbook/the-central-platform-team/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "AI Capability Engineers", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/ai-capability-engineers/", markdown: include_str!("../content/agentic-ai-transformation-playbook/ai-capability-engineers/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Forward-Deployed Engineers", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/forward-deployed-engineers/", markdown: include_str!("../content/agentic-ai-transformation-playbook/forward-deployed-engineers/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Domain Teams", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/domain-teams/", markdown: include_str!("../content/agentic-ai-transformation-playbook/domain-teams/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Centralised vs Federated", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/centralised-vs-federated/", markdown: include_str!("../content/agentic-ai-transformation-playbook/centralised-vs-federated/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "11. Roll Out and Scale".into(), pages: vec![
            PageSummary { date: "", title: "The First 30 Days", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/the-first-30-days/", markdown: include_str!("../content/agentic-ai-transformation-playbook/the-first-30-days/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Days 30–90", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/days-30-90/", markdown: include_str!("../content/agentic-ai-transformation-playbook/days-30-90/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Scale Across the Enterprise", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/scale-across-the-enterprise/", markdown: include_str!("../content/agentic-ai-transformation-playbook/scale-across-the-enterprise/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Avoid Platform Fragmentation", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/avoid-platform-fragmentation/", markdown: include_str!("../content/agentic-ai-transformation-playbook/avoid-platform-fragmentation/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
        Category { name: "12. Measure the Transformation".into(), pages: vec![
            PageSummary { date: "", title: "Adoption", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/adoption/", markdown: include_str!("../content/agentic-ai-transformation-playbook/adoption/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Business Value", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/business-value/", markdown: include_str!("../content/agentic-ai-transformation-playbook/business-value/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Platform Health", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/platform-health/", markdown: include_str!("../content/agentic-ai-transformation-playbook/platform-health/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
            PageSummary { date: "", title: "Continuous Improvement", description: "Placeholder lesson and research TODOs.", folder: "agentic-ai-transformation-playbook/continuous-improvement/", markdown: include_str!("../content/agentic-ai-transformation-playbook/continuous-improvement/index.md"), image: None, open_graph_image: None, author_image: None, author: None },
        ] },
    ] }
}
