use ssg_whiz::summaries::*;

pub fn summary() -> Summary {
    Summary {
        source_folder: "docs",
        categories: vec![
            Category {
                name: "Introducing Bionic".to_string(),
                pages: vec![PageSummary {
                    date: "",
                    title: "Introduction",
                    description: "Introducing Bionic",
                    folder: "docs/",
                    markdown: include_str!("../content/docs/index.md"),
                    image: None,
                    author_image: None,
                    author: None,
                }],
            },
            Category {
                name: "Learn Bionic".to_string(),
                pages: vec![
                    PageSummary {
                        date: "",
                        title: "The Console",
                        description: "The Console",
                        folder: "docs/guides/console/",
                        markdown: include_str!("../content/docs/guides/console/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Datasets",
                        description: "Datasets",
                        folder: "docs/guides/datasets/",
                        markdown: include_str!("../content/docs/guides/datasets/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "AI Assistants (Agentic RAG)",
                        description: "AI Assistants (Agentic RAG)",
                        folder: "docs/guides/aiassistants/",
                        markdown: include_str!("../content/docs/guides/aiassistants/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Teams",
                        description: "Teams",
                        folder: "docs/guides/teams/",
                        markdown: include_str!("../content/docs/guides/teams/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Local Bionic".to_string(),
                pages: vec![
                    PageSummary {
                        date: "",
                        title: "Docker Compose",
                        description: "Docker Compose",
                        folder: "docs/running-locally/docker-compose/",
                        markdown: include_str!(
                            "../content/docs/running-locally/docker-compose/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Kubernetes",
                        description: "Kubernetes",
                        folder: "docs/running-locally/kubernetes/",
                        markdown: include_str!(
                            "../content/docs/running-locally/kubernetes/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Connecting to Ollama",
                        description: "Connecting to Ollam",
                        folder: "docs/running-locally/ollama/",
                        markdown: include_str!("../content/docs/running-locally/ollama/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Private Cloud".to_string(),
                pages: vec![
                    PageSummary {
                        date: "",
                        title: "Installation Prerequisite",
                        description: "Install Bionic with Stack CLI",
                        folder: "docs/private-cloud/installation-prerequisite/",
                        markdown: include_str!(
                            "../content/docs/private-cloud/installation-prerequisite/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Install on a VM (K3s)",
                        description: "Install on a VM (K3s)",
                        folder: "docs/private-cloud/install-linux/",
                        markdown: include_str!(
                            "../content/docs/private-cloud/install-linux/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Digital Ocean",
                        description: "Digital Ocean",
                        folder: "docs/private-cloud/digital-ocean/",
                        markdown: include_str!(
                            "../content/docs/private-cloud/digital-ocean/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "AWS",
                        description: "AWS",
                        folder: "docs/private-cloud/aws/",
                        markdown: include_str!("../content/docs/private-cloud/aws/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Google Cloud",
                        description: "Google Cloud",
                        folder: "docs/private-cloud/gcloud/",
                        markdown: include_str!("../content/docs/private-cloud/gcloud/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Authentication".to_string(),
                pages: vec![PageSummary {
                    date: "",
                    title: "Single Sign On",
                    description: "Single Sign O",
                    folder: "docs/authentication/sso/",
                    markdown: include_str!("../content/docs/authentication/sso/index.md"),
                    image: None,
                    author_image: None,
                    author: None,
                }],
            },
            Category {
                name: "Configuring Bionic".to_string(),
                pages: vec![
                    PageSummary {
                        date: "",
                        title: "Cloudflare as Ingress",
                        description: "Cloudflare as Ingress",
                        folder: "docs/configuration/cloudflare/",
                        markdown: include_str!("../content/docs/configuration/cloudflare/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Connecting Airbyte",
                        description: "Connecting Airbyte",
                        folder: "docs/configuration/airbyte/",
                        markdown: include_str!("../content/docs/configuration/airbyte/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Configure Email",
                        description: "Configure Email",
                        folder: "docs/configuration/email/",
                        markdown: include_str!("../content/docs/configuration/email/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Upgrading Bionic",
                        description: "Upgrading Bionic",
                        folder: "docs/configuration/upgrades/",
                        markdown: include_str!("../content/docs/configuration/upgrades/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Role Based Access Control",
                        description: "Role Based Access Control",
                        folder: "docs/configuration/rbac/",
                        markdown: include_str!("../content/docs/configuration/rbac/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Database Backups",
                        description: "Database Backups",
                        folder: "docs/configuration/backups/",
                        markdown: include_str!("../content/docs/configuration/backups/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Licencing Bionic",
                        description: "Licencing Bioni",
                        folder: "docs/configuration/licencing/",
                        markdown: include_str!("../content/docs/configuration/licencing/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Runtime Encryption",
                        description: "Runtime Encryption",
                        folder: "docs/guides/encryption-at-rest/",
                        markdown: include_str!(
                            "../content/docs/guides/encryption-at-rest/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Automating Document Upload",
                        description: "Automating Document Upload",
                        folder: "docs/guides/uploading-documents/",
                        markdown: include_str!(
                            "../content/docs/guides/uploading-documents/index.md"
                        ),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Using the API",
                        description: "Using the API",
                        folder: "docs/guides/api/",
                        markdown: include_str!("../content/docs/guides/api/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Administration".to_string(),
                pages: vec![
                    PageSummary {
                        date: "",
                        title: "Managing Models",
                        description: "Managing Models",
                        folder: "docs/guides/managing-models/",
                        markdown: include_str!("../content/docs/guides/managing-models/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Guard Models",
                        description: "Guard Models",
                        folder: "docs/guides/guard-models/",
                        markdown: include_str!("../content/docs/guides/guard-models/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            /***Category {
                name: "How-To".to_string(),
                pages: vec![
                    PageSummary {
                        date: "",
                        title: "Deploying Jupyter Notebook",
                        description: "Deploying Jupyter Notebook",
                        folder: "docs/guides/jupyter/",
                        markdown: include_str!("../content/docs/guides/jupyter/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Visualising Agentic RAG",
                        description: "Visualising Agentic RAG",
                        folder: "docs/guides/visual-rag/",
                        markdown: include_str!("../content/docs/guides/visual-rag/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Coding CoPilot",
                        description: "Coding CoPilot",
                        folder: "docs/guides/code-copilot/",
                        markdown: include_str!("../content/docs/guides/code-copilot/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                    PageSummary {
                        date: "",
                        title: "Credit Card Categorising Assistant",
                        description: "Credit Card Categorising Assistan",
                        folder: "docs/guides/howtocategorise/",
                        markdown: include_str!("../content/docs/guides/howtocategorise/index.md"),
                        image: None,
                        author_image: None,
                        author: None,
                    },
                ],
            },
            Category {
                name: "Reference".to_string(),
                pages: vec![PageSummary {
                    date: "",
                    title: "Glossary",
                    description: "Glossary",
                    folder: "docs/guides/glossary/",
                    markdown: include_str!("../content/docs/guides/glossary/index.md"),
                    image: None,
                    author_image: None,
                    author: None,
                }],
            },**/
        ],
    }
}
