apiVersion: v1
kind: Service
metadata:
  name: selenium-development
spec:
  type: NodePort
  ports:
    - port: 5900
      targetPort: 5900
      nodePort: 30002
  selector:
    app: selenium-standalone-chrome