[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"

[dependencies]
tokio-postgres = { workspace = true, features = ["with-chrono-0_4"] }
cornucopia_async = { version = "0.6", features = ["with-serde_json-1"] }
deadpool-postgres = { version = "0.12.1", features = ["serde"] }
postgres = { version = "0.19", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"] }
postgres-protocol = "0.6"
postgres-types = { version = "0.2", features = ["derive", "with-uuid-1"] }
chrono = { workspace = true, features = ["serde"] }
time = { version = "0.3", default-features = false,  features = ["formatting", "serde", "parsing"] }
pgvector = { workspace = true, features = ["postgres"] }
tracing.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
futures.workspace = true
uuid = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["sync"] }
sqids = "0.4"

[features]
default = ["deadpool"]
deadpool = []
wasm-async = []
