// Editable draft: content, layout and linked sources are all in this file.
// Compile: typst compile agentic_ai_transformation_strategy.typ
#let ink = rgb("142D3B")
#let accent = rgb("087F8C")
#let pale = rgb("EDF5F5")
#set page(width: 320mm, height: 180mm, margin: (x: 18mm, y: 13mm), fill: rgb("FAFCFC"), footer: context {
  set text(size: 8pt, fill: rgb("62757E"))
  grid(columns: (1fr, auto), [IAN PURTON / BIONIC GPT · WORKING DRAFT · SEPTEMBER 2026], counter(page).display("01"))
})
#set text(font: "DejaVu Sans", size: 16pt, fill: ink)
#set par(leading: 0.5em, spacing: 0pt)
#let card(title, body) = block(fill: pale, radius: 3mm, inset: 6mm, width: 100%, height: 55mm)[
  #text(size: 21pt, weight: "bold", fill: accent, title)
  #v(4mm)
  #text(size: 14pt, body)
]
#let slide(section, title, sub, cards, take, refs, note) = {
  text(size: 10pt, weight: "bold", fill: accent, section)
  v(3mm)
  text(size: 26pt, weight: "bold", title)
  v(3mm)
  text(size: 14pt, fill: rgb("536873"), sub)
  v(7mm)
  grid(columns: (1fr, 1fr, 1fr), gutter: 5mm, ..cards.map(c => card(c.at(0), c.at(1))))
  v(5mm)
  text(size: 15pt, weight: "bold", take)
  v(1fr)
  text(size: 8pt, fill: rgb("62757E"), note)
  v(1.5mm)
  for (i, ref) in refs.enumerate() {
    text(size: 8pt, fill: accent)[#link(ref.at(1))[#(i+1). #ref.at(0)]]
    linebreak()
  }
  pagebreak()
}
#text(size: 11pt, weight: "bold", fill: accent)[STRATEGY / EDITABLE FIRST DRAFT]
#v(14mm)
#text(size: 39pt, weight: "bold")[A Defensible Strategy\ for Agentic AI Adoption]
#v(7mm)
#text(size: 19pt, fill: rgb("536873"))[Platform selection, citizen agents and enterprise capabilities]
#v(14mm)
#text(size: 20pt)[Equip people. Connect systems. Validate the work.]
#v(1fr)
#text(size: 10pt)[Ian Purton · Bionic GPT · September 2026]
#v(3mm)
#text(size: 9pt, fill: rgb("62757E"))[A proposed strategy grounded in research, company reports and technical documentation.\ Sources qualify individual claims; they do not endorse this entire strategy.]
#pagebreak()
#slide("THE OPPORTUNITY", "There are savings to be made.", "Start with documented results, then establish your own baseline.", (("14%","The 2023 NBER working paper reported roughly 14% more issues resolved per hour in customer support. Gains varied substantially by worker."),("Work redesign","McKinsey associates stronger AI outcomes with workflow redesign, leadership commitment and operational discipline."),("Local proof","Measure time, quality and review effort in your own work. Released capacity only becomes cash savings if costs actually fall."),), "Treat published results as evidence of possibility, not your business case.", (("NBER, Generative AI at Work (2023 working paper)","https://www.nber.org/papers/w31161"),("McKinsey, The State of AI (2026; respondent survey)","https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai"),), "Evidence: one workplace study and a broader self-reported survey; neither proves universal agent savings.")
#slide("THE ADOPTION ROUTE", "Make citizen agents a practical default.", "For everyday knowledge work, let employees describe the work and reuse approved capabilities.", (("Business-owned","An employee defines the objective, source information, expected output and review rules."),("Platform-enabled","Shared tools provide the models, files, integrations and execution needed to complete the task."),("Real precedent","Prosus reports 60,000+ agents built across 40,000+ employees. This is company-reported adoption, not independent proof of ROI."),), "Begin with employee-led, reviewable tasks; increase autonomy only after validation.", (("Prosus, The Coming Age of AI Colleagues (2026; company-reported)","https://staticcontents.investis.com/media/p/prosus/the-coming-age-of-ai-colleagues/report.html"),), "Recommendation supported by a published enterprise example; citizen agent is the terminology used in this draft.")
#slide("THE ADOPTION ROUTE", "Move from answers to completed work.", "Define the outcome before choosing how much autonomy it needs.", (("Research","Collect approved sources and produce a referenced briefing."),("Analyse","Reconcile a spreadsheet against source data and flag discrepancies."),("Act","Find a customer update, propose the correct CRM change and request approval."),), "Use a simple workflow when the steps are fixed; use an agent when the route needs flexibility.", (("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),), "Illustrative tasks. Anthropic distinguishes predefined workflows from model-directed agents.")
#slide("THE FOUNDATIONS", "You need a platform and training.", "Technology makes work possible. People make it useful.", (("Platform","Approved models, usable tools, enterprise access and controls. A platform team owns the shared foundation."),("Training","Teach task definition, source checking, output review and responsible delegation using real departmental work."),("Advocates","Support local champions with office hours, reusable examples and a route to report missing capabilities."),), "Fund enablement and operations alongside the technology.", (("Prosus, The Coming Age of AI Colleagues (2026; company-reported)","https://staticcontents.investis.com/media/p/prosus/the-coming-age-of-ai-colleagues/report.html"),("McKinsey, The State of AI (2026; respondent survey)","https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai"),), "Recommendation informed by the sources below.")
#slide("PLATFORM / 01", "Control the cost of completed work.", "An LLM gateway provides a common control point for model access and consumption.", (("See consumption","Attribute tokens, requests, latency and estimated spend to teams and tasks. Include failed runs and retries."),("Set limits","Use quotas, rate limits and alerts. Keep provider credentials out of agent instructions and user prompts."),("Choose models","Test lower-cost models on representative tasks. Change defaults only when quality and reliability remain acceptable."),), "Track cost per accepted result, not just the price per token.", (("Microsoft Learn, AI gateway capabilities","https://learn.microsoft.com/en-us/azure/api-management/genai-gateway-capabilities"),("Prosus, The Coming Age of AI Colleagues (2026; company-reported)","https://staticcontents.investis.com/media/p/prosus/the-coming-age-of-ai-colleagues/report.html"),), "Microsoft documents gateway controls; the selection and measurement approach is our recommendation.")
#slide("PLATFORM / 02", "Budget beyond model tokens.", "The platform cost includes the people and infrastructure needed to operate it.", (("Recurring cost","Licences or inference, compute, storage, gateways, monitoring, support and platform operations."),("Change cost","Integrations, training, evaluation, upgrades and migration. Include internal engineering time."),("Useful denominator","Monthly operating cost divided by accepted completed tasks. Track quality and task mix alongside it."),), "Self-hosted does not automatically mean cheaper; compare fully loaded costs.", (("McKinsey, The State of AI (2026; respondent survey)","https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai"),), "Proposed costing method. No vendor price comparison or savings forecast is implied.")
#slide("PLATFORM / 03", "Build a reusable integration catalogue.", "Connect capabilities once, then make them available to multiple tasks.", (("Find the systems","Inventory the systems of record, API owners, available operations and access constraints."),("Describe operations","Provide schemas, clear descriptions, examples and error behaviour. Prefer existing API contracts where practical."),("Expose selectively","Offer approved operations by role and task. Test discovery and correct use, not just connectivity."),), "A connector list is not enough: the required operation must work with the right permissions.", (("Microsoft Learn, API Management overview","https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts"),("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),), "API management and tool-interface guidance support this proposed integration approach.")
#slide("PLATFORM / 04", "Put API governance in the execution path.", "An API gateway can enforce controls; governance defines what those controls should be.", (("Governance","Name owners. Define permitted use, write approvals, API versions, quotas and change responsibilities."),("Gateway","Enforce credentials, routing, rate limits and telemetry. Reuse an existing enterprise gateway where it fits."),("System authority","Preserve record-level permissions in the destination system. Gateway authentication alone is insufficient."),), "The agent can request an action; policy and the target system decide whether it is allowed.", (("Microsoft Learn, API Management overview","https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts"),), "Microsoft documents gateway functions. The governance and permission recommendations extend that foundation.")
#slide("PLATFORM / 05", "Give agents tools to produce usable work.", "Files, execution and artifact generation determine which tasks the platform can complete.", (("Work with files","Read and write spreadsheets, documents and PDFs. Preserve formulas, provenance and editable outputs."),("Execute safely","Provide an isolated runtime with limits on time, resources, network access and secrets."),("Match the workload","Test a lightweight runtime for routine tasks; add a fuller sandbox when required libraries or tools need it."),), "Choose the execution environment from tested task requirements.", (("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),), "Proposed capability requirements; the sources do not establish a universal sandbox design.")
#slide("PLATFORM / 06", "Keep identity and data access intact.", "Agent access should follow the permissions and data boundaries of the organisation.", (("Identity","Use enterprise sign-in and scoped credentials. Define whose authority a scheduled job uses."),("Knowledge","Respect document permissions in search and retrieval. Show source references and recognise stale information."),("Data boundaries","Approve where prompts, files, logs and model traffic can go. Set retention and deletion policies."),), "Connecting data is only useful when access, provenance and handling are trustworthy.", (("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),("Microsoft Learn, API Management overview","https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts"),), "Recommended controls, informed by NIST risk management and API management guidance.")
#slide("PLATFORM / 07", "Make recurring work operable.", "Scheduling turns a useful task into a service that someone must own.", (("Run controls","Schedules or triggers, bounded retries, timeouts and protection against duplicate side effects."),("Lifecycle","An owner, versioned instructions, test cases, approved tools and a clear pause or retirement mechanism."),("Human review","Approval before consequential actions; failure notifications with enough context for someone to intervene."),), "Every recurring agent needs an owner and a way to stop it.", (("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),), "Operational requirements proposed for this strategy, rather than a feature list proven by the sources.")
#slide("PLATFORM / 08", "Evaluate and observe the whole task.", "A successful model response is only one part of a successful business result.", (("Before release","Test representative tasks, incorrect inputs, permission failures and unexpected tool responses."),("During operation","Record outcome, latency, model version, tool errors, review effort and cost. Redact sensitive logging."),("After changes","Repeat the relevant acceptance set when models, prompts, tools or permissions change."),), "Require evidence that the platform completes the work reliably.", (("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),), "Recommendation informed by the sources below.")
#slide("PLATFORM CHOICE", "Choose the deployment approach.", "Start from constraints, then compare the operating model.", (("Managed SaaS","Consider when approved data handling and available integrations meet the task requirements. Validate access to private systems."),("Self-hosted platform","Consider when customer-controlled infrastructure, model choice or internal integration needs justify operating the platform."),("Custom development","Consider when validated requirements remain unmet or a differentiated workflow warrants dedicated engineering."),), "Use the least complex approach that satisfies your acceptance criteria.", (("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),("Bionic GPT, product overview (vendor description)","https://bionic-gpt.com/"),), "Decision guidance. Bionic is an example of the self-hosted category, based on its own description.")
#slide("PLATFORM CHOICE", "Preserve the ability to change.", "Portability must be tested at the task level.", (("Models","Keep a repeatable acceptance set and exportable model settings. A compatible API does not guarantee equivalent behaviour."),("Tools and knowledge","Retain API contracts, source documents, permission mappings and integration documentation."),("Agent definitions","Export instructions, schedules and evaluation cases. Estimate the effort to recreate platform-specific features."),), "Ask for a migration demonstration, not just a claim of model independence.", (("Microsoft Learn, API Management overview","https://learn.microsoft.com/en-us/azure/api-management/api-management-key-concepts"),("Anthropic, Building Effective Agents (architecture guidance)","https://www.anthropic.com/engineering/building-effective-agents"),), "Proposed procurement criteria; portability depends on the implementation and contract.")
#text(size: 10pt, weight: "bold", fill: accent)[PLATFORM CHOICE / PROCUREMENT MATRIX]
#v(3mm)
#text(size: 26pt, weight: "bold")[Compare against explicit requirements.]
#v(4mm)
#text(size: 13pt)[Complete this worksheet with demonstrations and contractual evidence.]
#v(6mm)
#set table(inset: 2mm, stroke: 0.4pt + rgb("CFDCDD"))
#text(size: 10pt)[
#table(columns: (1.3fr, 1fr, 1fr, 1fr),
  table.header([*Criterion*], [*Managed SaaS*], [*Bionic GPT*], [*Custom platform*]),
  [Deployment], [Confirm approved hosting], [On-prem / private cloud¹], [Your architecture],
  [Models], [Confirm available options], [Hosted / private / local¹], [Your integrations],
  [Business systems], [Demonstrate required actions], [OpenAPI integration¹; test actions], [Implement and operate],
  [Files + execution], [Run acceptance tasks], [Run acceptance tasks], [Build and test],
  [Identity + controls], [Verify end-to-end], [Verify end-to-end], [Design and verify],
  [Scheduling + recovery], [Demonstrate failure handling], [Demonstrate failure handling], [Build and operate],
  [Model + API gateways], [Inspect native / external fit], [Inspect native / external fit], [Choose and integrate],
  [Portability], [Test exports and migration], [Test exports and migration], [Document and test],
  [Total cost + support], [Contract + internal operations], [Infrastructure + support + operations], [Engineering + operations],
)
]
#v(4mm)
#text(size: 13pt, weight: "bold")[Mark each requirement: meets / needs extension / fails, with evidence and an owner.]
#v(1fr)
#text(size: 8pt, fill: rgb("62757E"))[¹ Bionic product claims, not an independent feature assessment. Other cells are due-diligence prompts.\ Author affiliation: Bionic GPT. Compare named candidates within each category before deciding.]
#text(size: 8pt, fill: accent)[#link("https://bionic-gpt.com/")[1. Bionic GPT product overview]]
#pagebreak()
#slide("VALIDATION", "Test the platform on your work.", "Use a small acceptance set spanning the capabilities you need.", (("Documents + data","Create a briefing with verifiable citations; reconcile a workbook and preserve formulas."),("Enterprise actions","Read and update a test record with correct identity, permissions and approval behaviour."),("Recurring execution","Run a scheduled task through failures, retries and notification. Check for duplicate writes."),), "Set task-specific quality, reliability, cost and review thresholds before comparing options.", (("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),), "Illustrative acceptance tasks. Passing them supports only the capabilities and conditions actually tested.")
#slide("ENABLEMENT", "Train people to delegate and review.", "Teach a repeatable method using their own work.", (("Describe","State the objective, inputs, output format, constraints and how completion will be judged."),("Verify","Check facts, calculations, sources and proposed actions. Learn when to request specialist help."),("Reuse","Turn validated instructions into shared examples; nominate an owner before scheduling or broad distribution."),), "Measure whether training produces independently completed, reviewed tasks.", (("Prosus, The Coming Age of AI Colleagues (2026; company-reported)","https://staticcontents.investis.com/media/p/prosus/the-coming-age-of-ai-colleagues/report.html"),("McKinsey, The State of AI (2026; respondent survey)","https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai"),), "Proposed training curriculum, informed by enterprise adoption and workflow-redesign evidence.")
#slide("DELIVERY", "Expand through evidence and shared capabilities.", "Use decision gates rather than assuming every experiment should become production.", (("Establish","Name a sponsor and platform owner. Baseline tasks, approve data boundaries and connect initial systems."),("Validate","Train an initial group. Test useful tasks and address capability gaps. Proceed when quality and controls meet agreed thresholds."),("Expand","Share validated methods, add reusable integrations and support departmental ownership. Retire unsuccessful agents."),), "Scale the capabilities that enable useful work, then expand the work they support.", (("Prosus, The Coming Age of AI Colleagues (2026; company-reported)","https://staticcontents.investis.com/media/p/prosus/the-coming-age-of-ai-colleagues/report.html"),("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),), "Proposed rollout sequence. Scope and timing should follow organisational readiness.")
#slide("OUTCOMES", "Measure accepted work and realised value.", "Usage shows adoption. Outcomes show whether the investment is worthwhile.", (("Delivery","Accepted completion rate, task volume, quality checks, human review and recovery effort."),("Economics","Total operating cost; net time saved after review; cost per accepted task; evidenced revenue or cash effects."),("Adoption","Active repeat users, independently completed tasks and reuse of approved integrations and instructions."),), "Keep capacity released, cash savings and revenue gains as separate measures.", (("McKinsey, The State of AI (2026; respondent survey)","https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai"),("NIST, Generative AI Profile, AI 600-1 (2024)","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"),), "Proposed scorecard. Self-reported time savings need verification before financial attribution.")
#text(size: 10pt, weight: "bold", fill: accent)[SOURCE NOTES / REWRITING THE DRAFT]
#v(3mm)
#text(size: 26pt, weight: "bold")[Keep the argument and evidence distinct.]
#v(6mm)
#grid(columns: (1fr, 1fr), gutter: 9mm,
[
  #text(size: 18pt, weight: "bold")[How to read the sources]
  #v(4mm)
  #text(size: 13pt)[NBER supports a bounded productivity claim, not a universal saving. Prosus describes its own deployment and observations. McKinsey reports survey evidence and associations. Microsoft documents implementation capabilities. NIST provides risk-management guidance. Anthropic offers architecture guidance. Bionic describes its own product.]
], [
  #text(size: 18pt, weight: "bold")[Before publishing]
  #v(4mm)
  #text(size: 13pt)[Rewrite the recommendation in your own voice. Choose the target audience. Add organisation-specific thresholds and examples. Complete the matrix for named candidates. Recheck changing product features and sources. Keep the affiliation and evidence qualifications visible.]
])
#v(8mm)
#text(size: 14pt, weight: "bold")[The strategy is an argument to test, not a promise of a particular financial return.]
#v(1fr)
#text(size: 9pt, fill: rgb("62757E"))[Source links checked 30 September 2026. Live pages may change.\ The Typst source is self-contained and uses no external assets or packages.]
