apiVersion: v1
kind: Service
metadata:
  name: mixtral-8x7b
spec:
  selector:
    app: mixtral-8x7b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia

---

apiVersion: v1
kind: Pod
metadata:
  name: mixtral-8x7b
spec:
  runtimeClassName: nvidia
  containers:
  - name: bionic-gpt-operator
    image: ghcr.io/huggingface/text-generation-inference:0.4
    args: 
      - --model-id 
      - mistralai/Mixtral-8x7B-Instruct-v0.1
      - --quantize 
      - gptq
    resources:
      limits:
        nvidia.com/gpu: 1
