apiVersion: v1
kind: Service
metadata:
  name: mixtral-8x7b
  namespace: bionic-gpt
spec:
  selector:
    app: mixtral-8x7b
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixtral-8x7b-deployment
  namespace: bionic-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixtral-8x7b
  template:
    metadata:
      labels:
        app: mixtral-8x7b
    spec:
      containers:
      - name: bionic-gpt-operator
        image: ghcr.io/huggingface/text-generation-inference:sha-0eabc83
        args: 
          - --model-id 
          - mistralai/Mixtral-8x7B-Instruct-v0.1
          - --quantize 
          - gptq
