use crate::generator::*;

pub fn summary() -> Summary {
    Summary {
        source_folder: "docs",
        categories: vec![
            Category {
                name: "Getting Started".to_string(),
                pages: vec![Page {
                    date: "2025-09-30",
                    title: "Run Your First MCP Server",
                    description: "Launch your first AI assistant with Deploy in four steps.",
                    folder: "docs/",
                    markdown: include_str!("../content/docs/index.md"),
                    image: None,
                    author: None,
                    author_image: None,
                }],
            },
            Category {
                name: "Secure On-Premise".to_string(),
                pages: vec![
                    Page {
                        date: "",
                        title: "Secure On-Premise Overview",
                        description: "Why Deploy MCP runs on Kubernetes and how we harden it for enterprise use.",
                        folder: "docs/on-premise/",
                        markdown: include_str!("../content/docs/on-premise/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Install with the Deploy MCP Kubernetes Operator",
                        description: "Use the Kubernetes operator to manage Deploy MCP clusters on your infrastructure.",
                        folder: "docs/on-premise/install-operator/",
                        markdown: include_str!(
                            "../content/docs/on-premise/install-operator/index.md"
                        ),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Install on AWS",
                        description: "Provision Deploy MCP on Amazon EKS.",
                        folder: "docs/on-premise/aws/",
                        markdown: include_str!("../content/docs/on-premise/aws/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Install on Google Cloud",
                        description: "Bring Deploy MCP online on Google Kubernetes Engine.",
                        folder: "docs/on-premise/gcloud/",
                        markdown: include_str!("../content/docs/on-premise/gcloud/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Upgrading Deploy MCP",
                        description: "Upgrade the Deploy MCP operator and services.",
                        folder: "docs/on-premise/upgrades/",
                        markdown: include_str!("../content/docs/on-premise/upgrades/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Single Sign On",
                        description: "Integrate Deploy MCP with your identity provider.",
                        folder: "docs/on-premise/sso/",
                        markdown: include_str!("../content/docs/on-premise/sso/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Role Based Access Control",
                        description: "Manage Deploy MCP permissions with RBAC.",
                        folder: "docs/on-premise/rbac/",
                        markdown: include_str!("../content/docs/on-premise/rbac/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Database Backups",
                        description: "Protect Deploy MCP data with automated backups.",
                        folder: "docs/on-premise/backups/",
                        markdown: include_str!("../content/docs/on-premise/backups/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                    Page {
                        date: "",
                        title: "Apply Your Licence",
                        description: "Activate Deploy MCP with a licence key.",
                        folder: "docs/on-premise/licencing/",
                        markdown: include_str!("../content/docs/on-premise/licencing/index.md"),
                        image: None,
                        author: None,
                        author_image: None,
                    },
                ],
            },
        ],
    }
}
