name: Bionic Cluster (Create)

on:
  workflow_dispatch: # Triggers the workflow manually

jobs:
  bionic-cluster-create:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      FORCE_COLOR: 1
    steps:
        
    - uses: actions/checkout@v4

    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

    - name: Earthly version
      run: earthly --version 

    - name: Create Cluster
      run: |
        earthly +bionic-cluster-create \
          --AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID \
          --TUNNEL_TOKEN=$TUNNEL_TOKEN