name: Bionic Cluster (Delete)

on:
  workflow_dispatch: # Triggers the workflow manually

jobs:
  bionic-cluster-delete:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TOKEN: ${{ secrets.TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      FORCE_COLOR: 1
    steps:

    - uses: earthly/actions/setup-earthly@v1
      with:
        version: ^0.8.0
        
    - uses: actions/checkout@v4

    - name: Delete Cluster
      run: |
        earthly +bionic-cluster-delete \
          --AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID \
          --TOKEN=$TOKEN