name: Spell Check

on:
  push:
    branches:
    - main
    paths:
    - 'crates/static-website/content/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: PWD
      run: pwd

    - name: Spell Check
      run: docker run --rm -v $(pwd)/crates/static-website/content/:/workdir tmaier/markdown-spellcheck:latest --report "**/*.md"
    